const assert=require('node:assert/strict');
const L=require('../dist/logic.js');
const copy=x=>JSON.parse(JSON.stringify(x));
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name)}
test('Seed is a restorable backup',()=>assert.equal(L.validateBackup(L.seed()),true));
test('Unlabeled pickup cannot leave the customer',()=>{const o={...copy(L.seed().orders[4]),stage:'Menunggu Dijemput',evidence:{chat:true}};assert.throws(()=>L.advance(o,'Sudah Dijemput','Operator',L.DAY),/label/i);assert.equal(o.stage,'Menunggu Dijemput')});
test('Pickup can start at zero kg and is weighed upon arrival',()=>{const o={...copy(L.seed().orders[4]),weight:0,total:0};L.advance(o,'Menunggu Dijemput','Operator',L.DAY);o.evidence={chat:true,label:true,pickup:true,pickupAck:true};L.advance(o,'Sudah Dijemput','Operator',L.DAY);assert.throws(()=>L.advance(o,'Diterima Laundry','Operator',L.DAY),/berat/i);o.weight=3;o.evidence.weigh=true;L.advance(o,'Diterima Laundry','Operator',L.DAY);assert.equal(o.stage,'Diterima Laundry')});
test('Receipt is required before processing',()=>{const o={...copy(L.seed().orders[1]),evidence:{chat:true,label:true,weigh:true}};assert.throws(()=>L.advance(o,'Diproses','Operator',L.DAY),/resi/i)});
test('Quality control and packaging required before ready',()=>{const o=copy(L.seed().orders[0]);assert.throws(()=>L.advance(o,'Siap Diserahkan','Operator',L.DAY),/QC/);o.evidence.qc=true;o.evidence.packed=true;L.advance(o,'Siap Diserahkan','Operator',L.DAY);assert.equal(o.stage,'Siap Diserahkan')});
test('Customer handover acknowledgment is required for completion',()=>{const o=copy(L.seed().orders[2]);assert.throws(()=>L.advance(o,'Selesai','Operator',L.DAY),/penerima|konfirmasi/i);o.recipient=o.customer;o.evidence.handover=true;o.evidence.customerAck=true;L.advance(o,'Selesai','Operator',L.DAY);assert.equal(L.alertFor(o,L.DAY).days,0);assert.ok(o.durationHours>0);assert.equal(o.payment,'Lunas Cash')});
test('Skipped stages and closed/held transitions are rejected',()=>{for(const stage of ['Tertahan','Dibatalkan','Selesai'])assert.throws(()=>L.advance({...copy(L.seed().orders[1]),stage},'Pesanan Masuk','Operator',L.DAY));assert.throws(()=>L.advance(copy(L.seed().orders[1]),'Selesai','Operator',L.DAY),/Tahap/)});
test('Aging distinguishes 2 and 3 days and completed orders',()=>{let o=copy(L.seed().orders[0]);o.created='2026-09-08T09:00';assert.equal(L.alertFor(o,L.DAY).level,'orange');o.created='2026-09-07T09:00';assert.equal(L.alertFor(o,L.DAY).level,'red');o.stage='Selesai';assert.equal(L.alertFor(o,L.DAY).level,'green')});
test('Fresh overdue and checkout labels match their severity',()=>{const o=copy(L.seed().orders[0]);o.due=L.DAY+'T10:00';assert.equal(L.alertFor(o,L.DAY).label,'Lewat target');o.checkout=L.DAY+'T11:00';assert.equal(L.alertFor(o,L.DAY).level,'red');assert.equal(L.alertFor(o,L.DAY).label,'Lewat check-out')});
test('Cash difference separates float and customer receipts',()=>assert.equal(L.cashExpected(100000,68000),168000));
test('Only Owner may verify an already-deposited amount with a bank match',()=>{const s={status:'Sudah Disetor',deposit:68000,difference:0};assert.throws(()=>L.settleVerify(copy(s),'Operator',68000,'REF-DEMO'),/Owner/);assert.throws(()=>L.settleVerify({...s,status:'Belum Disetor'},'Owner',68000,'REF-DEMO'),/setor/i);assert.throws(()=>L.settleVerify(copy(s),'Owner',67000,'REF-DEMO'),/cocok/);L.settleVerify(s,'Owner',68000,'REF-DEMO');assert.equal(s.status,'Terverifikasi Owner')});
test('Verification retains cash discrepancies',()=>{const s={status:'Sudah Disetor',deposit:65000,difference:-3000};L.settleVerify(s,'Owner',65000,'REF-DEMO');assert.equal(s.difference,-3000);assert.match(s.status,/selisih/)});
test('Malformed backups cannot replace current data',()=>{for(const mutate of [s=>delete s.orders[0].payment,s=>delete s.settings.checklist,s=>delete s.invoices[0].history,s=>s.tenants=[],s=>s.settlements=[{id:'S-001'}],s=>s.orders.push(s.orders[0]),s=>s.orders[0].pic='missing',s=>s.invoices[0].paid=2e9,s=>s.settings.packages=[]]){const s=L.seed();mutate(s);assert.equal(L.validateBackup(s),false)}});
console.log('\n'+checks+' core workflow checks passed.');
