const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const C=require('../dist/journal-core.js'),F=require('../dist/finance-core.js'),TH=require('../dist/logic.js');
test('Journal range includes full ending minute in WIB, independent of device timezone',()=>{const r={start:'2026-09-10T08:00',end:'2026-09-10T09:00'};assert(C.matches('2026-09-10T01:00:00Z',r));assert(C.matches('2026-09-10T02:00:59.999Z',r));assert(!C.matches('2026-09-10T02:01:00Z',r));assert(!C.matches('2026-09-10T00:59:59Z',r));assert.equal(C.local('2026-09-09T17:00:00Z'),'2026-09-10T00:00');});
test('Custom timestamp range rejects inversion and undated events',()=>{assert(!C.valid({start:'2026-09-10T09:00',end:'2026-09-10T08:00'}));assert(!C.valid({start:'',end:''}));assert(Number.isNaN(C.timestamp('2026-09-10')));assert.equal(C.timestamp('2026-09-10T08:00'),Date.parse('2026-09-10T01:00Z'));});
test('Journal distinguishes event timestamps from service/accounting dates',()=>{const ops={orders:[{id:'O',customer:'Fiktif',created:'2026-09-09T15:00+07:00',completed:'2026-09-10T08:00+07:00',total:50000,history:[]}],reports:[{id:'R',date:'2026-09-09',submittedAt:'2026-09-10T09:00+07:00',activity:'Global',division:'Global'}]};const finance={transactions:[{id:'T',date:'2026-09-01',createdAt:'2026-09-02T08:00+07:00',postedAt:'2026-09-10T09:15+07:00',status:'Tercatat',description:'Latihan',unit:'laundry',amount:50000}]};const events=C.events(ops,finance).filter(e=>C.matches(e.at,{start:'2026-09-10T08:00',end:'2026-09-10T10:00'}));assert.deepEqual(events.map(e=>e.kind),['finance','report','completed']);});
const events={},elements={},node=()=>({innerHTML:'',textContent:'',className:'',open:false,classList:{add(){},remove(){}},showModal(){this.open=true},close(){this.open=false},querySelector(){return null},insertAdjacentHTML(){}});for(const k of ['#app','#dialog','#toast'])elements[k]=node();const ctx={console,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,Date,JSON,Number,String,Math,Promise,Set,Map,Blob,URL,FormData,TH,THServices:require('../dist/services-core.js'),THFinanceCore:F,localStorage:{getItem:()=>null,setItem(){},removeItem(){}},location:{protocol:'https:',origin:'https://local.test'},navigator:{onLine:true},setTimeout,clearTimeout,setInterval:()=>0,AbortSignal,document:{visibilityState:'visible',querySelector:s=>elements[s]||null,addEventListener:(n,f)=>(events[n]||(events[n]=[])).push(f),createElement:()=>({click(){}})},scrollTo(){},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);for(const file of ['journal-core.js','app.js','cloud.js','finance.js','date-filters.js','journal.js','readiness.js','services.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),ctx,{filename:file});
function fresh(role='Owner'){const ops=TH.seed();for(const k of Object.keys(ops))if(Array.isArray(ops[k]))ops[k]=[];ops.settings.packages=[];ops.settings.float=0;ops.settings.maxCash=0;const fin=F.seedFinance();for(const k of Object.keys(fin))if(Array.isArray(fin[k]))fin[k]=[];fin.policies=F.clone(F.defaultPolicies);ctx.THCloud.apply({revision:1,clock:'2026-09-10',operations:ops,finance:role==='Konsumen'?null:fin,member:{id:'owner',name:'Owner Contoh',role,status:'Aktif',profile:{},email:'owner@example.test'}});return ctx.THCloud.state;}
test('Owner journal, settings and start actions handle completely empty business arrays',()=>{fresh();const html=vm.runInContext('renderHome()',ctx);assert(html.includes('datetime-local'));assert(html.includes('Belum ada aktivitas'));assert(html.includes('Periksa kesiapan'));assert(!html.includes('NaN'));vm.runInContext('settingsForm()',ctx);assert(elements['#dialog'].innerHTML.includes('packageName0'));vm.runInContext('newOrder()',ctx);assert(elements['#dialog'].innerHTML.includes('Siapkan petugas'));});
test('Unlinked consumer has safe empty state, never a tenant fallback',()=>{fresh('Konsumen');vm.runInContext('renderConsumer()',ctx);assert(elements['#app'].innerHTML.includes('menautkan akun'));assert(!elements['#app'].innerHTML.includes('Alya'));});
test('Operator does not inherit arbitrary employee and Finance keeps actual role',()=>{fresh('Operator');assert.equal(vm.runInContext('ui.employee',ctx),'');fresh('Finance');assert.equal(vm.runInContext('ui.role',ctx),'Finance');});
test('A stale form blocks background data replacement',async()=>{fresh();elements['#dialog'].open=true;let called=[];ctx.THCloud.api=async path=>{called.push(path);return {revision:2,member:{id:'owner',role:'Owner',status:'Aktif',profile:{}}}};await ctx.THCloud.refresh();assert.deepEqual(called,['sync']);assert.equal(ctx.THCloud.state.revision,1);assert.equal(ctx.THCloud.remoteChanged,true);});
