const test=require('node:test'),assert=require('node:assert/strict'),S=require('../dist/services-core'),TH=require('../dist/logic'),F=require('../dist/finance-core'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
const by=id=>S.catalog().find(p=>p.id==='THL-'+id);
test('Thirty supplied services retain exact prices, durations, units and minima',()=>{const expected=[['bed-cover-l',35000,72,'Lembar',0],['bed-cover-m',30000,72,'Lembar',0],['bed-cover-s',25000,72,'Lembar',0],['cukedo',15000,3,'Load',0],['cukeli',20000,4,'Load',0],['express-shine',15000,6,'KG',2],['gorden',15000,72,'KG',0],['handuk-l',15000,48,'Helai',0],['handuk-m',10000,48,'Helai',0],['handuk-s',5000,48,'Helai',0],['iron-only',5000,48,'KG',0],['kain-panjang',4000,48,'PCS',0],['keset',8000,48,'Lembar',2],['mukena',8000,48,'Stel',0],['quick-clean',12000,24,'KG',2],['quick-iron',6000,24,'KG',0],['regular-refresh',6000,48,'KG',2],['rok-tile',12000,48,'PCS',0],['sajadah-jumbo',15000,48,'PCS',0],['sajadah-kecil',5000,48,'PCS',0],['sajadah-standar',8000,48,'PCS',0],['sarung',5000,48,'PCS',0],['selimut-l',25000,48,'Helai',0],['selimut-m',20000,48,'Helai',0],['selimut-s',15000,48,'Helai',0],['sprei-double',20000,48,'Lembar',0],['sprei-single',10000,48,'Helai',0],['sweater',10000,48,'PCS',0],['vitrase',18000,72,'KG',0],['vitrase-rimpel',20000,72,'KG',2]];assert.equal(S.catalog().length,30);for(const [id,...values] of expected){const p=by(id);assert.deepEqual([p.price,p.hours,p.unit,p.minQuantity],values,id);assert(S.valid(p));}});
test('Counted goods are never billed as kg, and minimum order is enforced without silent surcharge',()=>{assert.equal(S.quote(by('bed-cover-l'),0,2).total,70000);assert.equal(S.quote(by('mukena'),0,3).total,24000);assert.equal(S.quote(by('keset'),0,1).minimumMet,false);assert.equal(S.quote(by('regular-refresh'),1.5).minimumMet,false);assert.equal(S.quote(by('regular-refresh'),2.5).total,15000);assert.throws(()=>S.quote(by('bed-cover-l'),0,1.5),/bulat/);});
test('Two kg load boundaries and pickup quantities are explicit',()=>{for(const [kg,loads] of [[0,0],[0.1,1],[2,1],[2.01,2],[4,2],[4.01,3]]){assert.equal(S.quote(by('cukedo'),kg).total,loads*15000);assert.equal(S.quote(by('cukeli'),kg).total,loads*20000);}assert.match(S.rule(by('cukedo')),/load berikutnya/);});
test('Catalog upgrade changes only service settings and runs once, retaining subsequent owner edits',()=>{const ops=TH.seed(),before=JSON.stringify(ops.orders),tenants=JSON.stringify(ops.tenants);assert(S.install(ops));assert.equal(ops.settings.packages.length,30);assert.equal(JSON.stringify(ops.orders),before);assert.equal(JSON.stringify(ops.tenants),tenants);ops.settings.packages[0].price=36000;assert.equal(S.install(ops),false);assert.equal(ops.settings.packages[0].price,36000);});
test('Server pricing validator protects snapshots and supports item workflow evidence',()=>{const p=by('bed-cover-l'),o={serviceSnapshot:p,package:p.name,rate:p.price,total:70000,weight:0,quantity:2,billedQuantity:2,stage:'Diterima Laundry',evidence:{chat:true,label:true,weigh:true,receipt:true}};S.validateOrder(o,null,S.catalog(),'Owner');assert.equal(TH.gate(o,'Diproses'),'');assert.throws(()=>S.validateOrder({...o,total:1},null,S.catalog(),'Operator'),/Total/);S.validateOrder(o,structuredClone(o),[{...p,price:99000}],'Operator');assert.throws(()=>S.validateOrder({...o,serviceSnapshot:{...p,price:1}},o,S.catalog(),'Owner'),/lama/);assert.throws(()=>S.validateOrder({...o,serviceSnapshot:null},o,S.catalog(),'Owner'),/dihapus/);});
const node=()=>({innerHTML:'',textContent:'',open:false,classList:{add(){},remove(){},toggle(){}},querySelector(){return node()},querySelectorAll(){return[]},focus(){},setAttribute(){},showModal(){this.open=true},close(){this.open=false}}),elements={'#app':node(),'#dialog':node(),'#toast':node()};
const ctx={console,crypto:webcrypto,TH,THServices:S,THFinanceCore:F,Date,JSON,Number,String,Math,Promise,Set,Map,Blob,URL,FormData,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,setTimeout,clearTimeout,setInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{querySelector:s=>elements[s],querySelectorAll:()=>[],addEventListener(){}},location:{protocol:'https:',origin:'https://local.test'},navigator:{onLine:true},addEventListener(){},scrollTo(){}};ctx.window=ctx;vm.createContext(ctx);for(const file of ['journal-core.js','app.js','cloud.js','services.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),ctx);
const evaluate=s=>vm.runInContext(s,ctx);
function fresh(role='Owner'){evaluate(`db=TH.seed();THServices.install(db);db.orders=[];db.tenants=[];db.invoices=[];db.audit=[];ui.role='${role}';ui.employee='e1';THCloud.state={operations:JSON.parse(JSON.stringify(db)),member:{name:'Owner Contoh',role:'${role}',profile:{employeeId:'e1'}}};`);}
function input(overrides={}){return {tenantId:'new',customername:'Tamu Fiktif',customercontact:'WA-CONTOH-01',customertype:'Penginapan',customerbuilding:'C',customerfloor:'2',customerroom:'D01',customerroomType:'Executive',customercheckout:'2099-09-15T12:00',package:'0',weight:'0',quantity:'2',bags:'1',pic:'e1',due:'2099-09-12T12:00',mode:'Antar langsung',returnMode:'Antar ke kamar',chat:'on',label:'on',weigh:'on',receipt:'on',...overrides};}
function submit(v){ctx.input=v;return evaluate('submissions.order(input)');}
test('Owner and Operator create a lightweight guest and laundry order together, valid for backups',()=>{for(const role of ['Owner','Operator']){fresh(role);submit(input());const data=evaluate('JSON.parse(JSON.stringify(db))');assert.equal(data.orders.length,1);assert.equal(data.tenants.length,1);assert.equal(data.orders[0].total,70000);assert.equal(data.orders[0].floor,'2');assert.equal(data.orders[0].roomType,'Executive');assert.equal(data.orders[0].tenantId,data.tenants[0].id);assert.equal(data.tenants[0].rentKnown,false);assert.equal(data.tenants[0].start,'');assert.equal(data.invoices.length,0);assert(TH.validateBackup(data));}});
test('Invalid checkout, minimum, duplicate guest or evidence never partially creates a customer',()=>{for(const bad of [{customercheckout:''},{due:'2099-09-16T12:00'},{label:''},{quantity:'1',package:'12'}]){fresh();assert.throws(()=>submit(input(bad)));assert.equal(evaluate('db.tenants.length'),0);assert.equal(evaluate('db.orders.length'),0);}fresh();submit(input());assert.throws(()=>submit(input()),/sudah terdaftar/);assert.equal(evaluate('db.tenants.length'),1);});
test('Different guests can share a room; kost does not require invented checkout or rental value',()=>{fresh();submit(input());submit(input({customername:'Tamu Fiktif Dua',customercontact:'WA-CONTOH-02'}));submit(input({customertype:'Kost putri',customername:'Kost Fiktif',customercontact:'WA-CONTOH-03',customerbuilding:'A',customercheckout:''}));assert.equal(evaluate('db.tenants.length'),3);assert.equal(evaluate('db.tenants[2].end'),'');assert(TH.validateBackup(evaluate('db')));});
test('Pickup is finalized with saved service rate after catalog price edits; receipts and finance preserve units',()=>{fresh();submit(input({package:'3',mode:'Jemput',weight:'0',quantity:'0',label:'',weigh:'',receipt:''}));evaluate(`db.settings.packages[3].price=99999;submissions.evidence({weight:'2.1',pic:'e1',chat:'on',label:'on',weigh:'on',receipt:'on'}, {dataset:{id:db.orders[0].id}});`);assert.equal(evaluate('db.orders[0].total'),30000);assert.equal(evaluate('db.orders[0].quantity'),2);assert.match(evaluate('templateText(3,db.orders[0])'),/2 load \(2.1 kg\)/);assert.match(evaluate('templateText(3,db.orders[0])'),/Gedung C · Lantai 2 · Kamar D01/);evaluate(`Object.assign(db.orders[0],{stage:'Selesai',completed:'2026-09-10T10:00:00Z',recipient:'Tamu Fiktif'});Object.assign(db.orders[0].evidence,{qc:true,handover:true,customerAck:true});`);const finance=F.seedFinance();finance.transactions=[];finance.policies.approved=true;const candidates=F.candidates(evaluate('db'),finance,'owner');assert.equal(candidates[0].amount,30000);assert.equal(candidates[0].quantityUnit,'Load');assert.equal(candidates[0].quantity,2);finance.transactions.push(...candidates);assert.equal(F.candidates(evaluate('db'),finance,'owner').length,0);});
test('Operator evidence save preserves an Owner price correction',()=>{fresh();submit(input({mode:'Jemput',label:'',weigh:'',receipt:''}));evaluate(`db.orders[0].priceAdjustment={amount:-10000,reason:'Potongan disetujui Owner'};db.orders[0].total=60000;ui.role='Operator';submissions.evidence({weight:'0',quantity:'2',pic:'e1',chat:'on',label:'on',weigh:'on',receipt:'on'},{dataset:{id:db.orders[0].id}});`);assert.equal(evaluate('db.orders[0].total'),60000);const o=evaluate('JSON.parse(JSON.stringify(db.orders[0]))');S.validateOrder(o,structuredClone(o),S.catalog(),'Operator');const changed=structuredClone(o);delete changed.priceAdjustment;changed.total=70000;assert.throws(()=>S.validateOrder(changed,o,S.catalog(),'Operator'),/Owner/);});
