import Services from '../dist/services-core.js';
import Guide from '../dist/laundry-guide.js';
import {serviceSelection,quotePackages} from './laundry-pricing.mjs';
export class LaundryError extends Error{constructor(message,status=400){super(message);this.status=status}}
export const need=(v,m,s=400)=>{if(!v)throw new LaundryError(m,s)};
export const stamp=()=>new Date().toISOString();
export const roomCatalog=()=>[...Array.from({length:80},(_,i)=>({id:'A'+String(i+1).padStart(2,'0'),building:'A',type:'Kost'})),...Array.from({length:30},(_,i)=>({id:'B'+String(i+1).padStart(2,'0'),building:'B',type:'Kost'})),...['GRANDEXECUTIVE00','EXECUTIVE01','DELUXE02','SUPERIOR03','SUPERIOR04','SUPERIOR05','SUPERIOR06'].map(id=>({id:'C'+id,building:'C',type:'Penginapan'}))].map(r=>({...r,floor:'',active:false,checkout:'',roomType:r.id.replace(/^C/,'')}));
export const clean=(s,max=300)=>String(s||'').trim().slice(0,max);
export function customerFields(p,complete=true){
 const serviceIds=serviceSelection(p);
 const v={name:clean(p.name,100),contact:clean(p.contact,30),relationship:clean(p.relationship,80),method:p.method,serviceId:serviceIds[0],serviceIds,note:clean(p.note,1000)};
 need(['pickup','dropoff'].includes(v.method),'Pilih jemput atau antar ke counter.');
 if(complete){need(v.name.length>=2,'Nama minimal 2 karakter.');need(/^\+?[0-9 ()-]{8,24}$/.test(v.contact),'Nomor WhatsApp tidak valid.');need(v.relationship,'Pilih hubungan dengan kamar.');}return v;
}
const staff=m=>need(['Owner','Operator','Finance'].includes(m.role),'Akses petugas diperlukan.',403);
const owner=m=>need(m.role==='Owner','Tindakan ini memerlukan Owner.',403);
const active=o=>need(!['CANCELLED','COMPLETED','VOIDED','LINKED'].includes(o.status),'Order sudah ditutup.');
const confirmed=o=>need(o.kind==='THL'&&o.identity==='CONFIRMED','Identitas dan kamar harus terkonfirmasi.');
const accepted=o=>need(o.acceptedRevision===o.customerRevision,'Terima revisi terbaru sebelum melanjutkan.');
const paymentOpen=o=>need(!['CANCEL REQUESTED','RETURN REQUESTED','CANCELLED','VOIDED','LINKED'].includes(o.status),'Order dibatalkan; pembayaran baru ditutup.');
const reason=p=>{need(clean(p.reason).length>=5,'Alasan minimal 5 karakter.');return clean(p.reason)};
function incident(o,type,at,detail=''){if(!o.exceptions.some(x=>x.type===type&&x.open))o.exceptions.push({id:crypto.randomUUID(),type,open:true,at,detail,pic:o.assignedTo||'',due:new Date(Date.parse(at)+7200000).toISOString()});}
export function alerts(o,at=stamp()){const a=o.exceptions.filter(e=>e.open).map(e=>e.type);const age=(Date.parse(at)-Date.parse(o.createdAt))/60000;if(o.createdSource==='OPERATOR ASSISTED'&&!o.intakeProof&&age>5&&!['LINKED','VOIDED'].includes(o.status))a.push('Penerimaan fisik belum lengkap >5 menit');if(o.kind==='INT'&&o.status!=='LINKED')a.push('INT: identifikasi & karantina');if(o.identity!=='CONFIRMED'&&age>30)a.push(age>120?'Identitas tertunda >2 jam':'Identitas tertunda >30 menit');if(o.acceptedRevision&&o.acceptedRevision<o.customerRevision)a.push('Revisi belum diterima');if(!o.acceptedBy&&age>15&&!['CANCELLED','LINKED'].includes(o.status))a.push('Belum diterima >15 menit');if(o.room.checkout&&Date.parse(o.room.checkout)-Date.parse(at)<86400000&&!['COMPLETED','CANCELLED'].includes(o.status))a.push('Prioritas checkout <24 jam');if(o.pay.status==='PAID'&&o.set.status==='NOT CREATED')a.push('Pembayaran tanpa settlement');if(o.set.status==='IN TRANSIT'&&Date.parse(at)-Date.parse(o.pay.paidAt)>86400000)a.push('Setoran tertunda >24 jam');return [...new Set(a)];}
export function clearState(o){return o.status==='COMPLETED'&&o.pay.status==='PAID'&&o.set.status==='MATCHED'&&!o.ref.amount&&!o.exceptions.some(e=>e.open)?'CLEAR':o.status==='CANCELLED'&&!o.custody&&(!o.pay.received||o.ref.status==='REFUNDED')&&(!o.pay.received||o.ref.settlementAdjustment?.status==='MATCHED'&&['MATCHED','REFUND ADJUSTED'].includes(o.set.status))&&!o.exceptions.some(e=>e.open)?'CANCELLED CLEAR':'OPEN';}
export function newOrder({id,room,p,actor,kind='THL',at=stamp()}){return {id,kind,room:{id:room.id,building:room.building,floor:room.floor,type:room.type,roomType:room.roomType,checkout:room.checkout},customer:customerFields(p,kind==='THL'&&actor.role==='Customer'),createdAt:at,createdBy:actor.id,createdName:actor.name||'Pelanggan',initialSnapshot:customerFields(p,kind==='THL'&&actor.role==='Customer'),revisionHistory:[],acceptances:[],createdSource:actor.role==='Customer'?'CUSTOMER QR':'OPERATOR ASSISTED',intakeSource:actor.role==='Customer'?'customer_qr':kind==='INT'?'staff_unidentified':'staff_assisted',identity:actor.role==='Customer'?'CONFIRMED':kind==='INT'?'UNIDENTIFIED':'PENDING',customerRevision:1,acceptedRevision:0,acceptedBy:null,assignedTo:'',status:kind==='INT'?'QUARANTINE':'SUBMITTED',revision:1,custody:false,label:false,price:null,priceApproved:false,pay:{status:'NOT CREATED',received:0,attempts:[]},set:{status:'NOT CREATED'},ref:{status:'NONE',amount:0},exceptions:[],notification:{status:'QUEUED',attempts:0,provider:'NOT CONNECTED'},simulation:false};}
export function transition(original,action,p,m,proofs=[],at=stamp()){
 const o=structuredClone(original),isCustomer=m.role==='Customer';if(!isCustomer)staff(m);else need(['revise','cancel','confirm-identity','reject-ownership','approve-price'].includes(action),'Action pelanggan tidak tersedia.',403);
 if(o.status==='ON HOLD')need(['review-sop','refund-account','resume','cancel','incident','assign','label-lost','relabel','resolve-exception','notify-retry','submit-set','approve-set','refund-approve','refund-pay','refund-reconcile'].includes(action),'Order ditahan. Lanjutkan tahap sebelumnya terlebih dahulu.');
 const evidence=(key='proofId',live=false)=>{const x=proofs.find(x=>x.id===p[key]&&x.order_id===o.id);need(x,'Lampirkan bukti untuk order ini.');if(live)need(x.capture==='live','Ambil foto langsung dari kamera.');return x.id};
 if(action==='review-sop'){
  need(/^(0[1-9]|1[0-9]|2[0-8])$/.test(p.scenarioId||''),'Pilih skenario SOP 01–28.');
  need(clean(p.note,1000).length>=10,'Catat hasil pemeriksaan minimal 10 karakter.');
  const proof=p.proofId?evidence():null;
  o.sopReviews=(o.sopReviews||[]).filter(r=>r.scenarioId!==p.scenarioId||r.role!==m.role);
  o.sopReviews.push({scenarioId:p.scenarioId,role:m.role,by:m.id,name:m.name,at,note:clean(p.note,1000),proof,signature:Guide.reviewKey(original)});
 }
 else if(action==='incident'){need(clean(p.type),'Jenis kendala wajib.');const why=reason(p);const proofId=evidence();o.exceptions.push({id:crypto.randomUUID(),type:clean(p.type,100),open:true,at,detail:why,proof:proofId,pic:clean(p.pic)||m.id,due:p.due||new Date(Date.parse(at)+7200000).toISOString()});}
 else if(action==='set-process-policy'){owner(m);active(o);o.requirePaidBeforeProcess=!!p.required;}
 else if(action==='assign'){active(o);need(clean(p.assignedTo),'Pilih PIC.');if(o.assignedTo&&o.assignedTo!==p.assignedTo)reason(p);o.assignmentHistory=o.assignmentHistory||[];o.assignmentHistory.push({from:o.assignedTo,to:clean(p.assignedTo),by:m.id,name:m.name,reason:clean(p.reason),at});o.assignedTo=clean(p.assignedTo);}
 else if(action==='accept'){active(o);need(o.kind==='THL','Identifikasi INT terlebih dahulu.');need(!o.acceptedBy||o.acceptedRevision<o.customerRevision,'Order sudah diterima petugas lain.',409);if(!o.acceptedBy)o.acceptedBy={id:m.id,name:m.name,at};o.acceptedRevision=o.customerRevision;o.acceptances.push({revision:o.customerRevision,by:m.id,name:m.name,at});o.assignedTo=o.assignedTo||m.id;if(['SUBMITTED','AWAITING PICKUP','AWAITING DROPOFF'].includes(o.status))o.status=o.customer.method==='pickup'?'AWAITING PICKUP':'AWAITING DROPOFF';}
 else if(action==='revise'){active(o);need(!['IN PROCESS','READY FOR HANDOVER'].includes(o.status),'Order sedang diproses; hubungi petugas.');need(!o.pay.received,'Order telah dibayar; koreksi melalui petugas.');o.revisionHistory.push({revision:o.customerRevision,customer:o.customer,at,by:m.id});o.customer=customerFields(p);o.customerRevision++;o.priceApproved=false;delete o.priceApproval;delete o.priceApprovalProof;delete o.processAuthorization;o.pay.attempts.forEach(a=>{if(a.status==='PENDING')a.status='VOIDED'});if(o.pay.status!=='NOT CREATED')o.pay.status='VOIDED';}
 else if(action==='confirm-identity'){active(o);need(o.kind==='THL','INT harus ditautkan Owner ke kamar terverifikasi.');if(!isCustomer){owner(m);o.identityProof=evidence();reason(p);}o.customer=customerFields({...o.customer,...p});o.identity='CONFIRMED';if(o.status==='QUARANTINE')o.status=o.quarantinedFrom|| (o.custody?(o.customer.method==='pickup'?'PICKED UP':'RECEIVED AT COUNTER'):'SUBMITTED');delete o.quarantinedFrom;o.exceptions.filter(e=>e.type==='OWNERSHIP REJECTED').forEach(e=>e.open=false);}
 else if(action==='reject-ownership'){active(o);o.identity='UNIDENTIFIED';if(o.status!=='QUARANTINE')o.quarantinedFrom=o.status;o.status='QUARANTINE';incident(o,'OWNERSHIP REJECTED',at);}
 else if(action==='receive'){active(o);need(!o.custody,'Barang sudah diterima.');if(o.kind==='THL')accepted(o);o.intakeProof=evidence('proofId',true);need(Number.isInteger(+p.bags)&&+p.bags>0&&+p.bags<=100,'Jumlah kantong 1–100.');o.bags=+p.bags;o.custody=true;o.receivedAt=at;o.receivedBy=m.id;o.receivedName=m.name;o.location=clean(p.location);need(o.location,'Isi lokasi penyimpanan.');const actual=p.arrivedAt?Date.parse(p.arrivedAt):Date.parse(at);need(Number.isFinite(actual)&&actual<=Date.parse(at),'Waktu barang tiba tidak valid.');o.arrivedAt=new Date(actual).toISOString();if(Date.parse(at)-actual>300000)incident(o,'INTAKE >5 MINUTES',at);o.label=true;o.labelCode=o.id;o.status=o.kind==='INT'||o.identity==='UNIDENTIFIED'?'QUARANTINE':o.customer.method==='pickup'?'PICKED UP':'RECEIVED AT COUNTER';}
 else if(action==='label-lost'){active(o);need(o.custody,'Barang belum diterima.');o.label=false;incident(o,'LABEL MISSING',at,reason(p));}
 else if(action==='relabel'){active(o);need(o.custody,'Barang belum diterima.');o.labelProof=evidence('proofId',true);o.label=true;o.labelCode=o.id;o.exceptions.filter(x=>['LABEL MISSING','RELABEL REQUIRED'].includes(x.type)).forEach(x=>x.open=false);}
 else if(action==='weigh'){
  active(o);need(['PICKED UP','RECEIVED AT COUNTER','PRICE CONFIRMATION PENDING'].includes(o.status),'Hasil timbang hanya dapat diedit sebelum proses dimulai.');
  need(o.kind==='THL'&&o.custody&&o.label,'Timbang memerlukan THL, barang, dan label.');accepted(o);
  need(!o.pay.received,'Harga telah dibayar. Gunakan refund atau order tambahan.');
  const proof=evidence('proofId',true),price=quotePackages(p,o.customer);
  o.priceHistory=o.priceHistory||[];
  if(o.price)o.priceHistory.push({price:structuredClone(o.price),proof:o.weighProof,approval:o.priceApproval||null,approvalProof:o.priceApprovalProof||null,by:m.id,name:m.name,at,reason:clean(p.reason,1000)||'Koreksi hasil timbang'});
  const revision=(o.price?.revision||0)+1;
  o.weighProof=proof;o.weighedBy={id:m.id,name:m.name,at};o.price={...price,at,revision};
  o.priceApproved=false;delete o.priceApproval;delete o.priceApprovalProof;delete o.processAuthorization;
  o.notification={...o.notification,status:'QUEUED',note:'Harga terbaru menunggu persetujuan pelanggan di tautan order.'};
  o.pay.attempts.forEach(x=>{if(!x.received&&['PENDING','PENDING VERIFICATION'].includes(x.status))x.status='VOIDED'});delete o.pay.proof;delete o.pay.submittedBy;o.pay.status=o.pay.attempts.length?'VOIDED':'NOT CREATED';o.status='PRICE CONFIRMATION PENDING';
 }
 else if(action==='approve-price'){
  paymentOpen(o);confirmed(o);accepted(o);need(o.price,'Belum ada harga final.');
  if(!isCustomer)o.priceApprovalProof=evidence();o.priceApproved=true;
  o.priceApproval={by:m.id,name:m.name||'Pelanggan',at,revision:o.price.revision||1,via:isCustomer?'CUSTOMER PORTAL':'RECORDED WITH PROOF'};
  o.exceptions.filter(e=>e.type==='PROCESS WITHOUT CUSTOMER APPROVAL'&&e.open).forEach(e=>{e.open=false;e.resolvedBy=m.id;e.atResolved=at;e.reason='Persetujuan harga sudah diterima';});
 }
 else if(action==='create-pay'){paymentOpen(o);confirmed(o);accepted(o);need(o.price&&o.priceApproved,'Harga final harus disetujui.');need(!['PAID','OVERPAID'].includes(o.pay.status),'Pembayaran sudah diterima.');need(['Cash','Transfer','QRIS Demo'].includes(p.method),'Metode belum tersedia.');need(p.method!=='QRIS Demo'||o.simulation,'QRIS provider belum terhubung. Gunakan Transfer/Cash.');need(!o.pay.received||o.pay.method===p.method,'Sisa pembayaran memakai metode awal. Pembayaran campuran memerlukan rekonsiliasi terpisah.');o.pay.attempts.forEach(a=>{if(a.status==='PENDING')a.status='VOIDED'});o.pay.id='PAY'+o.id.slice(3);o.pay.method=p.method;o.pay.status='PENDING';o.pay.attempts.push({id:o.pay.id+'-A'+String(o.pay.attempts.length+1).padStart(2,'0'),status:'PENDING',amount:o.price.total-o.pay.received,at});}
 else if(action==='expire-pay'){need(o.pay.status==='PENDING','Tidak ada attempt pending.');o.pay.status='EXPIRED';o.pay.attempts.at(-1).status='EXPIRED';}
 else if(action==='payment-proof'){paymentOpen(o);need(['PENDING','PENDING VERIFICATION','UNDERPAID'].includes(o.pay.status),'Buat PAY terlebih dahulu.');o.pay.proof=evidence();o.pay.submittedBy=m.id;o.pay.status='PENDING VERIFICATION';}
 else if(action==='verify-pay'){paymentOpen(o);confirmed(o);accepted(o);need(o.priceApproved,'Harga belum disetujui.');need(['PENDING','PENDING VERIFICATION','UNDERPAID'].includes(o.pay.status),'PAY tidak menunggu verifikasi.');if(o.pay.method!=='Cash'){need(['Owner','Finance'].includes(m.role),'Verifikasi transfer memerlukan Owner/Finance.',403);need(o.pay.submittedBy&&m.id!==o.pay.submittedBy,'Pemeriksa berbeda dari pengunggah bukti.');need(clean(p.reference).length>=5,'Isi referensi mutasi bank independen.');}o.pay.receiptProof=evidence();need(Number.isSafeInteger(+p.amount)&&+p.amount>0&&+p.amount<=100000000,'Jumlah pembayaran tidak valid.');need(!o.pay.attempts.at(-1).received,'Buat attempt baru untuk tambahan pembayaran.');o.pay.received+=+p.amount;o.pay.receivedBy=m.id;o.pay.paidAt=at;o.pay.reference=clean(p.reference);o.pay.status=o.pay.received===o.price.total?'PAID':o.pay.received<o.price.total?'UNDERPAID':'OVERPAID';o.pay.attempts.at(-1).status=o.pay.status;Object.assign(o.pay.attempts.at(-1),{received:+p.amount,receivedAt:at,receivedBy:m.id,method:o.pay.method,proof:o.pay.receiptProof,reference:clean(p.reference)});if(o.pay.method==='Cash')o.pay.receiptNo='CSH'+o.id.slice(3)+'-'+o.pay.attempts.length;if(o.set.status==='MATCHED'){o.set.history=o.set.history||[];o.set.history.push({...o.set,history:undefined});}o.set={...o.set,id:'SET'+o.id.slice(3),status:'IN TRANSIT',gross:o.pay.received,receivedBy:m.id};if(o.pay.status==='OVERPAID')incident(o,'OVERPAYMENT',at);}
 else if(action==='submit-set'){need(['IN TRANSIT','SHORT','OVER'].includes(o.set.status),'Settlement belum tersedia.');o.set.history=o.set.history||[];if(o.set.proof)o.set.history.push({...o.set,history:undefined});o.set.proof=evidence();need(Number.isSafeInteger(+p.actual)&&+p.actual>=0&&Number.isSafeInteger(+p.fee)&&+p.fee>=0&&+p.fee<=o.set.gross,'Nominal setoran/biaya tidak valid.');const priorMatches=(o.set.history||[]).filter(x=>x.status==='MATCHED');const lastMatched=priorMatches.at(-1);need(!lastMatched||+p.actual>=lastMatched.actual&&+p.fee>=lastMatched.fee,'Isi total setoran dan biaya kumulatif; nilai terdahulu tetap tersimpan.');o.set.actual=+p.actual;o.set.fee=+p.fee;o.set.expected=o.set.gross-o.set.fee;o.set.account=clean(p.account);o.set.reference=clean(p.reference);need(o.set.account&&o.set.reference,'Rekening dan referensi setoran wajib.');o.set.submittedBy=m.id;o.set.status='PENDING VERIFICATION';}
 else if(action==='approve-set'){need(['Owner','Finance'].includes(m.role),'Owner/Finance diperlukan.',403);need(o.set.status==='PENDING VERIFICATION','Settlement belum diajukan.');need(m.id!==o.set.submittedBy&&m.id!==o.set.receivedBy&&!o.pay.attempts.some(a=>a.receivedBy===m.id),'Pemeriksa tidak boleh penerima uang atau pengaju setoran.');o.set.approvedBy=m.id;o.set.approvedAt=at;o.set.status=o.set.actual===o.set.expected?'MATCHED':o.set.actual<o.set.expected?'SHORT':'OVER';if(o.set.status!=='MATCHED')incident(o,'SET '+o.set.status,at);}
 else if(action==='process'){
  active(o);confirmed(o);accepted(o);
  need(!o.requirePaidBeforeProcess||o.pay.status==='PAID','Owner mewajibkan lunas sebelum proses.');
  need(o.custody&&o.label&&o.weighProof&&o.price,'Lengkapi barang, label, dan bukti timbang sebelum proses.');
  need(o.status==='PRICE CONFIRMATION PENDING','Tahap proses tidak valid.');
  need(clean(p.batch)&&p.scannedId===o.id,'Pindai label THL yang sama dan isi nomor batch mesin.');
  if(!o.priceApproved){
   need(['Owner','Operator'].includes(m.role),'Pengecualian proses memerlukan petugas operasional.',403);
   need(p.proceedWithoutApproval===true,'Harga belum disetujui. Minta persetujuan atau catat pengecualian proses.');
   need(['CUSTOMER_BUSY','VERBAL_INSTRUCTION','LONG_WAIT'].includes(p.overrideContext),'Pilih kondisi pengecualian.');
   need(clean(p.reason,1000).length>=20,'Jelaskan alasan melanjutkan minimal 20 karakter.');
   o.processAuthorization={by:m.id,name:m.name,at,reason:clean(p.reason,1000),context:p.overrideContext,priceRevision:o.price.revision||1,customerRevision:o.customerRevision,waitMinutes:Math.max(0,Math.floor((Date.parse(at)-Date.parse(o.price.at))/60000))};
   incident(o,'PROCESS WITHOUT CUSTOMER APPROVAL',at,o.processAuthorization.reason);
  }
  o.batch={id:clean(p.batch),scannedId:p.scannedId,actor:m.id,at};o.status='IN PROCESS';
 }
 else if(action==='ready'){need(o.status==='IN PROCESS','Order belum diproses.');need(o.custody&&o.label,'Barang dan label harus tersedia untuk QC.');confirmed(o);accepted(o);o.qcProof=evidence('proofId',true);o.status='READY FOR HANDOVER';}
 else if(action==='paylater'){owner(m);o.paylater={by:m.id,reason:reason(p),at};}
 else if(action==='handover'){need(o.status==='READY FOR HANDOVER','Order belum siap serah.');need(o.priceApproved,'Persetujuan harga pelanggan masih diperlukan sebelum serah terima.');accepted(o);confirmed(o);need(o.custody&&o.label,'Barang dan label harus tersedia untuk serah terima.');need(o.pay.status==='PAID'||o.paylater,'Pembayaran belum lunas; perlu persetujuan bayar nanti dari Owner.');o.handoverProof=evidence();need(clean(p.recipient).length>=2,'Nama penerima wajib.');o.handover={recipient:clean(p.recipient),by:m.id,at};o.custody=false;o.status='COMPLETED';}
 else if(action==='cancel'){active(o);need(!['CANCEL REQUESTED','RETURN REQUESTED'].includes(o.status),'Permintaan pembatalan sudah tercatat.');if(o.status==='ON HOLD'){o.status=o.heldFrom;delete o.heldFrom;}if(o.status==='QUARANTINE'&&o.quarantinedFrom)o.status=o.quarantinedFrom;const why=reason(p);o.cancelReason=why;o.pay.attempts.forEach(a=>{if(!a.received&&['PENDING','PENDING VERIFICATION'].includes(a.status))a.status='VOIDED'});if(!o.pay.received&&o.pay.status!=='NOT CREATED')o.pay.status='VOIDED';if(o.pay.received){o.ref={id:'REF'+o.id.slice(3),status:'REQUESTED',amount:o.pay.received,reason:why,requestedAt:at};}if(o.status==='IN PROCESS'||o.status==='READY FOR HANDOVER'){o.status='CANCEL REQUESTED';o.requiresOwner=true;}else if(o.custody)o.status='RETURN REQUESTED';else o.status=o.acceptedBy?'CANCEL REQUESTED':'CANCELLED';}
 else if(action==='approve-cancel'){need(o.status==='CANCEL REQUESTED','Tidak ada permintaan pembatalan.');if(o.requiresOwner)owner(m);o.cancelDecision={by:m.id,reason:reason(p),at};o.status=o.custody?'RETURN REQUESTED':'CANCELLED';}
 else if(action==='return'){need(o.status==='RETURN REQUESTED','Tidak ada permintaan pengembalian.');o.returnProof=evidence();need(clean(p.recipient),'Nama penerima diperlukan.');o.custody=false;o.status='CANCELLED';}
 else if(action==='record-return-proof'){
  owner(m);
  need(o.kind==='THL'&&o.status==='CANCELLED'&&!o.custody&&o.intakeProof&&!o.returnProof,'Bukti tambahan hanya untuk pesanan batal yang barangnya sudah keluar dan belum memiliki bukti pengembalian.');
  need(o.exceptions.some(e=>e.open&&['LABEL MISSING','RELABEL REQUIRED','OWNERSHIP REJECTED'].includes(e.type)),'Tidak ada kendala pengembalian yang perlu dilengkapi.');
  const proofId=evidence(),recipient=clean(p.recipient),why=reason(p);
  need(recipient.length>=2,'Nama penerima wajib.');
  o.returnProof=proofId;
  o.returnEvidence={recipient,by:m.id,name:m.name,recordedAt:at,reason:why};
 }
 else if(action==='refund-approve'){owner(m);need(o.ref.status==='REQUESTED','Refund belum diminta.');o.ref.status='APPROVED';o.ref.approvedBy=m.id;o.ref.reason=reason(p);}
 else if(action==='refund-pay'){need(['Owner','Finance'].includes(m.role),'Owner/Finance diperlukan.',403);need(['APPROVED','PARTIALLY REFUNDED'].includes(o.ref.status),'Refund belum disetujui.');o.ref.proof=evidence();if(p.cashAccount)need(['1102','1101K'].includes(p.cashAccount),'Refund memakai bank operasional atau kas kecil.');need(Number.isSafeInteger(+p.amount)&&+p.amount>0&&+p.amount<=o.ref.amount-(o.ref.paid||0),'Nominal refund tidak valid.');o.ref.paid=(o.ref.paid||0)+ +p.amount;o.ref.status=o.ref.paid===o.ref.amount?'REFUNDED':'PARTIALLY REFUNDED';o.ref.paidBy=m.id;o.ref.at=at;o.ref.payments=o.ref.payments||[];o.ref.payments.push({amount:+p.amount,proof:o.ref.proof,by:m.id,name:m.name,at,reference:clean(p.reference),cashAccount:p.cashAccount||null});o.ref.settlementAdjustment={amount:o.ref.paid,status:'REQUIRES RECONCILIATION',originalSet:o.set.id};}
 else if(action==='refund-account'){need(['Owner','Finance'].includes(m.role),'Owner/Finance diperlukan.',403);const payment=o.ref.payments?.[Number(p.paymentIndex)];need(Number.isInteger(Number(p.paymentIndex))&&payment&&!payment.cashAccount,'Pilih refund yang rekening asalnya belum tercatat.');need(['1102','1101K'].includes(p.cashAccount),'Pilih bank operasional atau kas kecil.');payment.accountEvidence=evidence();payment.cashAccount=p.cashAccount;payment.accountCorrection={by:m.id,name:m.name,at,reason:reason(p)};}
 else if(action==='refund-reconcile'){need(['Owner','Finance'].includes(m.role),'Owner/Finance diperlukan.',403);need(o.ref.status==='REFUNDED'&&o.ref.settlementAdjustment?.status==='REQUIRES RECONCILIATION','Selesaikan pengembalian dana terlebih dahulu.');need(!(o.ref.payments||[]).some(x=>x.by===m.id)&&o.ref.paidBy!==m.id,'Pemeriksa berbeda dari pengembali dana.');need(clean(p.reference).length>=5,'Referensi pencocokan dana wajib.');const cash=o.pay.attempts.filter(a=>a.method==='Cash').reduce((n,a)=>n+(a.received||0),0),cashReturned=Number(p.cashReturned||0);need(Number.isSafeInteger(cashReturned)&&cashReturned>=0&&cashReturned<=cash&&cashReturned<=o.ref.paid,'Cash dikembalikan tidak valid.');need(!cashReturned||!(o.ref.payments||[]).some(x=>['1102','1101K'].includes(x.cashAccount)),'Refund dari bank/kas kecil tidak mengurangi cash penerimaan; setorkan cash yang masih dipegang.');need(o.set.status!=='MATCHED'||cashReturned===0,'Cash yang sudah disetor tidak dapat dikurangi lagi.');if(cashReturned===o.pay.received&&cashReturned>0&&o.set.status!=='MATCHED'){o.set.history=o.set.history||[];o.set.history.push({...o.set,history:undefined});o.set.status='REFUND ADJUSTED';o.set.expected=0;}o.ref.settlementAdjustment={...o.ref.settlementAdjustment,cashReturned,status:'MATCHED',proof:evidence(),reason:reason(p),reference:clean(p.reference),reviewedBy:m.id,reviewedName:m.name,at};}
 else if(action==='resolve-exception'){owner(m);const e=o.exceptions.find(e=>e.id===p.exceptionId);need(e,'Pilih pengecualian.');if(['LABEL MISSING','RELABEL REQUIRED'].includes(e.type))need(o.label||o.status==='CANCELLED'&&!o.custody&&o.returnProof,'Label belum diperbaiki.');if(e.type==='PROCESS WITHOUT CUSTOMER APPROVAL')need(o.priceApproved||o.status==='CANCELLED'&&!o.custody,'Persetujuan harga pelanggan masih belum diterima.');if(e.type==='OWNERSHIP REJECTED')need(o.identity==='CONFIRMED'||o.status==='CANCELLED'&&!o.custody&&o.returnProof,'Identitas belum terkonfirmasi.');if(e.type.startsWith('SET '))need(o.set.status==='MATCHED','Settlement belum cocok.');e.proof=evidence();e.reason=reason(p);e.open=false;e.resolvedBy=m.id;}
 else if(action==='hold'){active(o);need(!['CANCEL REQUESTED','RETURN REQUESTED','QUARANTINE'].includes(o.status),'Selesaikan pembatalan atau identitas lebih dahulu.');o.heldFrom=o.status;o.status='ON HOLD';incident(o,'ON HOLD',at,reason(p));}
 else if(action==='resume'){need(o.status==='ON HOLD'&&o.heldFrom,'Tidak ada tahap tertahan yang dapat dilanjutkan.');reason(p);o.status=o.heldFrom;delete o.heldFrom;o.exceptions.filter(e=>e.type==='ON HOLD'&&e.open).forEach(e=>{e.open=false;e.resolvedBy=m.id;e.reason=clean(p.reason);e.atResolved=at});}
 else if(action==='void'){owner(m);active(o);need(!o.handoverProof,'Order yang sudah diserahkan memerlukan koreksi keuangan.');need(!o.custody&&!o.pay.received,'Kembalikan barang/selesaikan uang terlebih dahulu.');o.status='VOIDED';o.voidReason=reason(p);}
 else if(action==='notify-retry'){o.notification.status='QUEUED';o.notification.attempts++;o.notification.note='Menunggu koneksi penyedia WhatsApp; belum dikirim.';}
 else throw new LaundryError('Tindakan tidak didukung.',404);
 o.updatedAt=at;return o;
}
