import {accountingState} from './laundry-journal.mjs';
import {resolveStaffIdentity} from './staff-auth.mjs';
import {need,clean,stamp,roomCatalog,newOrder,transition,alerts,clearState,LaundryError} from './laundry-engine.mjs';
import Services from '../dist/services-core.js';
const J=JSON.stringify,P=JSON.parse;
const q=(env,sql,...v)=>env.DB.prepare(sql).bind(...v),first=(env,sql,...v)=>q(env,sql,...v).first();
export const hash=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const json=(v,status=200)=>new Response(J(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});
const bearer=req=>req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';
const safe=o=>{const v=structuredClone(o);v.alerts=alerts(o);v.clear=clearState(o);return v};
function customerView(o){return {id:o.id,room:o.room,customer:o.customer,status:o.status,identity:o.identity,revision:o.revision,customerRevision:o.customerRevision,acceptedRevision:o.acceptedRevision,acceptedName:o.acceptedBy?.name||'',createdAt:o.createdAt,price:o.price,priceApproved:o.priceApproved,processingException:o.processAuthorization?{at:o.processAuthorization.at,reason:o.processAuthorization.reason,name:o.processAuthorization.name}:null,pay:{status:o.pay.status,received:o.pay.received,method:o.pay.method},ref:{status:o.ref.status,amount:o.ref.amount},custody:o.custody,proofs:[['Penerimaan barang',o.intakeProof],['Hasil timbang',o.weighProof],['Quality check',o.qcProof],['Serah terima',o.handoverProof],['Pengembalian barang',o.returnProof]].filter(x=>x[1]).map(([label,id])=>({label,id})),notification:o.notification,clear:clearState(o)};}
const dateKey=()=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date()).replaceAll('/','');
async function nextId(env,room,kind='THL'){const key=kind+'-'+dateKey()+(kind==='THL'?'-'+room:'');const n=await q(env,'INSERT INTO laundry_counters(id,value) VALUES(?,1) ON CONFLICT(id) DO UPDATE SET value=value+1 RETURNING value',key).first();return key+'-'+(kind==='INT'?String(n.value).padStart(3,'0'):n.value);}
async function actor(req,env){const user=await resolveStaffIdentity(req,env),id=user?.id;need(id,'Masuk ke Top Hills untuk akses petugas.',401);const m=await first(env,'SELECT * FROM members WHERE id=?',id);need(m?.status==='Aktif'&&['Owner','Operator','Finance'].includes(m.role),'Akses petugas belum diberikan Owner.',403);return m;}
async function roomByToken(env,t){need(/^[a-f0-9]{64}$/.test(t),'QR tidak valid atau telah diganti.',404);const row=await first(env,'SELECT * FROM laundry_rooms WHERE token_hash=?',await hash(t));need(row,'QR tidak valid atau telah diganti.',404);const r=P(row.data);need(r.active,'Kamar belum aktif. Hubungi petugas untuk bantuan.',409);return r;}
async function getOrder(env,id){const row=await first(env,'SELECT * FROM laundry_orders WHERE id=?',id);need(row,'Order tidak ditemukan.',404);return {...P(row.data),revision:row.revision};}
async function customerActor(req,env,id){
 const row=await first(env,"SELECT token_hash,json_extract(data,'$.kind') AS kind FROM laundry_orders WHERE id=?",id);
 need(row&&row.kind==='THL'&&row.token_hash===await hash(bearer(req)),'Tautan order tidak valid.',404);
 const staffId=(await resolveStaffIdentity(req,env))?.id;let readOnly=false;
 if(staffId){
  const person=await first(env,'SELECT role,status FROM members WHERE id=?',staffId);
  if(person?.status==='Aktif'&&['Owner','Operator','Finance'].includes(person.role)){
   need(person.role==='Owner','Tautan ini hanya untuk pelanggan. Gunakan Meja Laundry untuk bekerja.',403);
   need(req.method==='GET','Owner hanya dapat melihat halaman pelanggan. Catat tindakan melalui Meja Laundry.',403);
   readOnly=true;
  }
 }
 return {id:'customer:'+id,name:'Pelanggan',role:'Customer',readOnly};
}
async function audit(env,id,m,action,data){await q(env,'INSERT INTO laundry_events VALUES(?,?,?,?,?,?)',crypto.randomUUID(),id,m.id,stamp(),action,J({...data,actorName:m.name||'Pelanggan'})).run();}
async function insert(env,o,secret,key){await q(env,'INSERT OR IGNORE INTO laundry_orders(id,room_id,token_hash,submission_key,revision,status,created_at,data) VALUES(?,?,?,?,?,?,?,?)',o.id,o.room.id,await hash(secret),key,1,o.status,o.createdAt,J(o)).run();const row=await first(env,'SELECT * FROM laundry_orders WHERE submission_key=?',key);need(row,'Pengiriman bertabrakan. Coba ulang.',409);return P(row.data);}
async function mutate(env,old,o,m,p){const h=await hash(J(p)),key=m.id+':'+p.mutationId;need(/^[a-zA-Z0-9-]{16,80}$/.test(p.mutationId||''),'Kunci pengiriman tidak valid.');const prior=await first(env,'SELECT * FROM laundry_mutations WHERE id=?',key);if(prior){need(prior.order_id===old.id&&prior.hash===h,'Kunci pengiriman sudah digunakan.',409);return getOrder(env,old.id);}need(p.revision===old.revision,'Data berubah di perangkat lain. Muat ulang sebelum melanjutkan.',409);o.revision=old.revision+1;need(J(o).length<150000,'Riwayat order perlu diarsipkan sebelum ditambah.');const marker=crypto.randomUUID();o.lastMutation=marker;const guard="EXISTS(SELECT 1 FROM laundry_orders WHERE id=? AND json_extract(data,'$.lastMutation')=?)";const result=await env.DB.batch([q(env,'UPDATE laundry_orders SET revision=?,status=?,data=? WHERE id=? AND revision=?',o.revision,o.status,J(o),o.id,old.revision),q(env,`INSERT INTO laundry_events SELECT ?,?,?,?,?,? WHERE ${guard}`,crypto.randomUUID(),o.id,m.id,stamp(),p.action,J({revision:o.revision,reason:p.reason||'',status:o.status,actorName:m.name||'Pelanggan',actionData:p}),o.id,marker),q(env,`INSERT INTO laundry_mutations SELECT ?,?,?,? WHERE ${guard}`,key,o.id,h,J({revision:o.revision}),o.id,marker)]);need(result[0].meta.changes===1,'Order baru saja diperbarui petugas lain. Muat ulang.',409);return o;}
export async function laundryRoute(req,env){const u=new URL(req.url),path=u.pathname,publicPath=path.startsWith('/api/portal/');need(env.DB&&env.BUCKET,'Database belum tersedia.',503);if(req.method!=='GET'){need(req.headers.get('Origin')===u.origin&&req.headers.get('X-Top-Hills')==='1','Permintaan lintas situs ditolak.',403);need(['POST'].includes(req.method),'Tidak tersedia: riwayat tidak dapat dihapus.',405);need(+req.headers.get('Content-Length')<6000000,'Permintaan terlalu besar.',413);}
 if(path==='/api/portal/room'&&req.method==='GET'){const room=await roomByToken(env,bearer(req));return json({room:{id:room.id,building:room.building,floor:room.floor,roomType:room.roomType,type:room.type,checkout:room.checkout},services:Services.catalog()});}
 let m;if(!publicPath)m=await actor(req,env);
 if(path==='/api/laundry/rooms'&&req.method==='GET'){const [roomRows,assignees]=await env.DB.batch([q(env,'SELECT id,revision,data,token_hash IS NOT NULL AS has_qr FROM laundry_rooms ORDER BY id'),q(env,"SELECT id,name FROM members WHERE status='Aktif' AND role IN ('Owner','Operator')")]);const rows=roomRows.results;return json({rooms:rows.map(r=>({...P(r.data),revision:r.revision,hasQR:!!r.has_qr})),member:{id:m.id,name:m.name,role:m.role},assignees:assignees.results,services:Services.catalog()});}
 if(path==='/api/laundry/summary'&&req.method==='GET'){const summary=await first(env,`SELECT count(*) AS total, sum(CASE WHEN json_extract(data,'$.acceptedBy') IS NOT NULL THEN 1 ELSE 0 END) AS accepted, sum(CASE WHEN json_extract(data,'$.custody')=1 THEN COALESCE(json_extract(data,'$.bags'),0) ELSE 0 END) AS physicalBags, sum(CASE WHEN json_extract(data,'$.set.status')!='MATCHED' THEN MAX(0,COALESCE((SELECT sum(COALESCE(json_extract(value,'$.received'),0)) FROM json_each(laundry_orders.data,'$.pay.attempts') WHERE json_extract(value,'$.method')='Cash'),0)-CASE WHEN json_extract(data,'$.ref.settlementAdjustment.status')='MATCHED' THEN COALESCE(json_extract(data,'$.ref.settlementAdjustment.cashReturned'),0) ELSE 0 END) ELSE 0 END) AS cashInTransit, sum(CASE WHEN json_extract(data,'$.kind')='INT' AND status!='LINKED' THEN 1 ELSE 0 END) AS openInt, sum(CASE WHEN json_extract(data,'$.createdSource')='OPERATOR ASSISTED' THEN 1 ELSE 0 END) AS assisted FROM laundry_orders`);const shifts=(await q(env,"SELECT id,actor,at,action,data FROM laundry_events WHERE action IN ('SHIFT SUBMITTED','SHIFT REVIEWED') ORDER BY at DESC LIMIT 30").all()).results;return json({summary,shifts});}
 if(path==='/api/laundry/orders'&&req.method==='GET'){const start=u.searchParams.get('start')||'2000-01-01',end=u.searchParams.get('end')||'2100-01-01';need(/^\d{4}-\d{2}-\d{2}$/.test(start)&&/^\d{4}-\d{2}-\d{2}$/.test(end)&&start<=end,'Rentang tanggal tidak valid.');const cursor=u.searchParams.get('cursor')||'',search=clean(u.searchParams.get('search'),100),stage=clean(u.searchParams.get('status'),50),pattern='%'+search+'%';const rows=(await q(env,`SELECT data,revision FROM laundry_orders WHERE created_at>=? AND created_at<? AND id>? AND (?='' OR id LIKE ? OR json_extract(data,'$.customer.name') LIKE ? OR room_id LIKE ?) AND (?='' OR status=?) ORDER BY id LIMIT 101`,new Date(start+'T00:00:00+07:00').toISOString(),new Date(Date.parse(end+'T00:00:00+07:00')+86400000).toISOString(),cursor,search,pattern,pattern,pattern,stage,stage).all()).results;return json({orders:rows.slice(0,100).map(r=>safe({...P(r.data),revision:r.revision})),nextCursor:rows.length>100?P(rows[99].data).id:null});}
 if(path==='/api/portal/order'||path==='/api/laundry/order'){const id=u.searchParams.get('id');if(req.method==='GET'){if(publicPath){const viewer=await customerActor(req,env,id);return json({order:customerView(await getOrder(env,id)),readOnly:viewer.readOnly});}const [orders,financial,proofs,events]=await env.DB.batch([q(env,'SELECT data,revision FROM laundry_orders WHERE id=?',id),q(env,'SELECT data FROM finance_transactions WHERE source_key LIKE ?','portal:'+id+':%'),q(env,'SELECT id,capture,mime,created_at FROM laundry_proofs WHERE order_id=?',id),q(env,'SELECT actor,at,action,data FROM laundry_events WHERE order_id=? ORDER BY at DESC LIMIT 100',id)]);const row=orders.results[0];need(row,'Order tidak ditemukan.',404);const o={...P(row.data),revision:row.revision};return json({order:safe(o),accounting:accountingState(o,financial.results.map(r=>P(r.data))),proofs:proofs.results,events:events.results});}}

 if(path==='/api/portal/proof'&&req.method==='GET'){const id=u.searchParams.get('orderId');await customerActor(req,env,id);const o=await getOrder(env,id);const proofId=u.searchParams.get('id');need(customerView(o).proofs.some(p=>p.id===proofId),'Bukti tidak tersedia.',404);const proof=await first(env,'SELECT * FROM laundry_proofs WHERE id=? AND order_id=?',proofId,id);need(proof,'Bukti tidak tersedia.',404);const obj=await env.BUCKET.get(proof.object_key);need(obj,'File belum tersedia.',404);return new Response(obj.body,{headers:{'Content-Type':proof.mime,'Cache-Control':'private, no-store','Content-Security-Policy':"sandbox; default-src 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});}
 if(path==='/api/laundry/proof'&&req.method==='GET'){const proof=await first(env,'SELECT * FROM laundry_proofs WHERE id=?',u.searchParams.get('id'));need(proof,'Bukti tidak ditemukan.',404);const obj=await env.BUCKET.get(proof.object_key);need(obj,'File belum tersedia.',404);return new Response(obj.body,{headers:{'Content-Type':proof.mime,'Cache-Control':'no-store','Content-Security-Policy':"sandbox; default-src 'none'",'X-Content-Type-Options':'nosniff'}});}
 if((path==='/api/laundry/proof'||path==='/api/portal/proof')&&req.method==='POST'){const f=await req.formData(),proofOrderId=clean(f.get('orderId')),o=!publicPath&&/^SHIFT-[a-f0-9-]{36}$/.test(proofOrderId)?{id:proofOrderId}:await getOrder(env,proofOrderId),file=f.get('file');if(publicPath){m=await customerActor(req,env,o.id);need(!['IN PROCESS','READY FOR HANDOVER','COMPLETED','CANCEL REQUESTED','RETURN REQUESTED','CANCELLED','VOIDED','ON HOLD'].includes(o.status),'Tahap ini dikunci; hubungi petugas untuk bukti tambahan.');}need(file&&file.size>0&&file.size<=5000000,'Bukti JPG/PNG/PDF maksimal 5 MB.');const b=new Uint8Array(await file.arrayBuffer());const mime=b[0]===255&&b[1]===216?'image/jpeg':b[0]===137&&b[1]===80?'image/png':new TextDecoder().decode(b.slice(0,5))==='%PDF-'?'application/pdf':'';need(mime,'File harus JPG/PNG/PDF.');const count=await first(env,'SELECT count(*) AS n FROM laundry_proofs WHERE order_id=?',o.id);need(count.n<40,'Maksimal 40 bukti per order.');const id=crypto.randomUUID(),key='laundry/'+o.id+'/'+id,capture=!publicPath&&f.get('capture')==='live'&&mime.startsWith('image/')?'live':'upload',createdAt=stamp();await env.BUCKET.put(key,b,{httpMetadata:{contentType:mime}});try{await q(env,'INSERT INTO laundry_proofs VALUES(?,?,?,?,?,?,?)',id,o.id,key,mime,capture,m.id,createdAt).run();}catch(e){await env.BUCKET.delete(key);throw e;}if(publicPath){const updated=structuredClone(o);updated.revisionHistory.push({revision:o.customerRevision,customer:o.customer,photoId:id,by:m.id,at:stamp()});updated.customerRevision++;await mutate(env,o,updated,m,{id:o.id,action:'customer-photo',revision:o.revision,mutationId:crypto.randomUUID(),proofId:id});}return json({id,capture,proof:{id,capture,mime,created_at:createdAt}});}
 need(req.method==='POST','Metode tidak tersedia.',405);const p=await req.json();need(J(p).length<20000,'Data formulir terlalu panjang.');
 if(path==='/api/laundry/shift'){need(Number.isInteger(+p.physicalBags)&&+p.physicalBags>=0&&Number.isSafeInteger(+p.cash)&&+p.cash>=0,'Jumlah paket dan uang fisik tidak valid.');need(/^[a-zA-Z0-9-]{16,80}$/.test(p.mutationId||''),'Kunci pengiriman diperlukan.');const proof=await first(env,'SELECT id,order_id,actor FROM laundry_proofs WHERE id=?',p.proofId);need(proof&&/^SHIFT-[a-f0-9-]{36}$/.test(proof.order_id)&&proof.actor===m.id,'Unggah bukti closing shift milik Anda.');need(clean(p.note).length>=5,'Catatan handover shift wajib.');const expected=await first(env,`SELECT sum(CASE WHEN json_extract(data,'$.custody')=1 THEN COALESCE(json_extract(data,'$.bags'),0) ELSE 0 END) AS bags,sum(CASE WHEN json_extract(data,'$.set.status')!='MATCHED' THEN MAX(0,COALESCE((SELECT sum(COALESCE(json_extract(value,'$.received'),0)) FROM json_each(laundry_orders.data,'$.pay.attempts') WHERE json_extract(value,'$.method')='Cash'),0)-CASE WHEN json_extract(data,'$.ref.settlementAdjustment.status')='MATCHED' THEN COALESCE(json_extract(data,'$.ref.settlementAdjustment.cashReturned'),0) ELSE 0 END) ELSE 0 END) AS cash FROM laundry_orders`);const result={physicalBags:+p.physicalBags,cash:+p.cash,expectedBags:expected.bags||0,expectedCash:expected.cash||0,bagDifference:+p.physicalBags-(expected.bags||0),cashDifference:+p.cash-(expected.cash||0),proofId:p.proofId,note:clean(p.note,1000),pic:m.id,actorName:m.name,due:new Date(Date.now()+86400000).toISOString(),status:'PENDING REVIEW'};const id='shift:'+m.id+':'+p.mutationId;await q(env,'INSERT OR IGNORE INTO laundry_events VALUES(?,?,?,?,?,?)',id,'SHIFT',m.id,stamp(),'SHIFT SUBMITTED',J(result)).run();return json({id});}
 if(path==='/api/laundry/shift-review'){need(m.role==='Owner','Owner diperlukan.',403);const source=await first(env,"SELECT * FROM laundry_events WHERE id=? AND action='SHIFT SUBMITTED'",p.id);need(source,'Laporan shift tidak ditemukan.');need(source.actor!==m.id,'Reviewer harus berbeda dari pembuat laporan.');need(clean(p.note).length>=5,'Catatan review wajib.');const report=P(source.data),resolved=!report.bagDifference&&!report.cashDifference;await q(env,'INSERT OR IGNORE INTO laundry_events VALUES(?,?,?,?,?,?)','review:'+p.id,'SHIFT',m.id,stamp(),'SHIFT REVIEWED',J({sourceId:p.id,status:resolved?'MATCHED':'EXCEPTION OPEN',note:clean(p.note),actorName:m.name,pic:source.actor,due:report.due})).run();return json({status:resolved?'MATCHED':'EXCEPTION OPEN'});}
 if(path==='/api/laundry/rooms/init'){need(m.role==='Owner','Owner diperlukan.',403);await env.DB.batch(roomCatalog().map(r=>q(env,'INSERT OR IGNORE INTO laundry_rooms(id,data) VALUES(?,?)',r.id,J(r))));return json({initialized:117});}
 if(path==='/api/laundry/room'){need(m.role==='Owner','Hanya Owner dapat mengatur kamar.',403);const row=await first(env,'SELECT * FROM laundry_rooms WHERE id=?',p.id);need(row,'Kamar tidak ditemukan.');need(row.revision===p.revision,'Data kamar berubah. Muat ulang.',409);const room=P(row.data);room.floor=clean(p.floor,20);room.roomType=clean(p.roomType,80);room.active=!!p.active;room.checkout=p.checkout?new Date(p.checkout).toISOString():'';need(!room.active||room.floor&&room.roomType,'Lengkapi lantai dan jenis kamar sebelum mengaktifkan.');need(!room.active||room.type!=='Penginapan'||room.checkout&&Date.parse(room.checkout)>Date.now(),'Checkout penginapan aktif harus di masa depan.');const t=p.rotate?token():null;const result=await q(env,'UPDATE laundry_rooms SET data=?,revision=revision+1,token_hash=CASE WHEN ? IS NULL THEN token_hash ELSE ? END WHERE id=? AND revision=?',J(room),t,t?await hash(t):null,p.id,p.revision).run();need(result.meta.changes===1,'Data kamar berubah.',409);await audit(env,p.id,m,'ROOM UPDATE',{active:room.active,rotated:!!t});return json({room,qrPath:t?'/checkin#room='+t:null});}
 if(path==='/api/portal/submit'){const staffId=(await resolveStaffIdentity(req,env))?.id;if(staffId){const person=await first(env,'SELECT role,status FROM members WHERE id=?',staffId);need(!person||!['Owner','Operator','Finance'].includes(person.role)||person.status!=='Aktif','Petugas memakai Check-in dibantu dari Meja Laundry.',403);}const room=await roomByToken(env,bearer(req));need(!room.checkout||Date.parse(room.checkout)>Date.now(),'Masa tinggal berakhir. Hubungi petugas.',409);need(!p.roomId||p.roomId===room.id,'Kamar dikunci dari QR.',403);need(/^[a-f0-9]{64}$/.test(p.orderToken||''),'Kunci pelacakan tidak valid.');const key=await hash('qr:'+bearer(req)+':'+p.orderToken),prior=await first(env,'SELECT data FROM laundry_orders WHERE submission_key=?',key);if(prior)return json({order:customerView(P(prior.data))});const recent=await first(env,'SELECT count(*) n FROM laundry_orders WHERE room_id=? AND created_at>?',room.id,new Date(Date.now()-3600000).toISOString());need(recent.n<20,'Batas pengiriman kamar tercapai. Hubungi petugas.',429);const a={id:'guest',role:'Customer'},id=await nextId(env,room.id);const o=newOrder({id,room,p,actor:a});o.device=clean(req.headers.get('User-Agent'),250);o.roomTokenId=await hash(bearer(req));const saved=await insert(env,o,p.orderToken,key);return json({order:customerView(saved)},201);}
 if(path==='/api/laundry/assisted'){need(['Owner','Operator'].includes(m.role),'Petugas operasional diperlukan.',403);need(/^[a-zA-Z0-9-]{16,80}$/.test(p.mutationId||''),'Kunci pengiriman diperlukan.');const key=m.id+':assisted:'+p.mutationId;const prior=await first(env,'SELECT data FROM laundry_orders WHERE submission_key=?',key);if(prior)return json({order:safe(P(prior.data))});const row=await first(env,'SELECT data FROM laundry_rooms WHERE id=?',clean(p.roomId));let room=row?P(row.data):{id:'UNKNOWN',building:'',floor:'',type:'',roomType:'',checkout:''};const kind=room.active&&(!room.checkout||Date.parse(room.checkout)>Date.now())?'THL':'INT';if(kind==='INT')room={...room,id:'UNKNOWN'};const id=await nextId(env,room.id,kind);const o=newOrder({id,room,p,actor:m,kind}),secret=token();o.device=clean(req.headers.get('User-Agent'),250);return json({order:safe(await insert(env,o,secret,key)),...(m.role==='Owner'&&kind==='THL'?{trackingPath:'/checkin#order='+id+'&key='+secret}:{})});}
 if(path==='/api/laundry/tracking'){need(m.role==='Owner','Hanya Owner yang dapat membuka tautan pelanggan untuk pemeriksaan.',403);const old=await getOrder(env,p.id);need(old.kind==='THL','Catatan barang sementara tidak memiliki tautan pelanggan.',400);const secret=token();await q(env,'UPDATE laundry_orders SET token_hash=? WHERE id=?',await hash(secret),old.id).run();await audit(env,old.id,m,'ROTATE TRACKING',{});return json({trackingPath:'/checkin#order='+old.id+'&key='+secret});}
 if(path==='/api/laundry/link-int'){need(m.role==='Owner','Owner diperlukan untuk memverifikasi kamar.',403);const old=await getOrder(env,p.id);need(old.kind==='INT'&&old.status==='QUARANTINE','Pilih INT terbuka.');need(old.revision===p.revision,'INT berubah. Muat ulang.',409);const row=await first(env,'SELECT data FROM laundry_rooms WHERE id=?',p.roomId),r=row&&P(row.data);need(r?.active&&(!r.checkout||Date.parse(r.checkout)>Date.now()),'Kamar aktif diperlukan.');const proof=await first(env,'SELECT id FROM laundry_proofs WHERE id=? AND order_id=?',p.proofId,old.id);need(proof&&clean(p.reason).length>=5,'Bukti identifikasi dan alasan wajib.');const secret=token(),o=newOrder({id:await nextId(env,r.id),room:r,p:{...old.customer,...p},actor:m});o.identity='CONFIRMED';o.linkedInt=old.id;o.custody=old.custody;o.bags=old.bags;o.receivedAt=old.receivedAt;o.receivedBy=old.receivedBy;o.receivedName=old.receivedName;o.arrivedAt=old.arrivedAt;o.location=old.location;o.createdBy=old.createdBy;o.createdName=old.createdName;o.linkedBy={id:m.id,name:m.name,at:stamp()};o.status=o.custody?(o.customer.method==='pickup'?'PICKED UP':'RECEIVED AT COUNTER'):'SUBMITTED';o.intakeProof=old.intakeProof?crypto.randomUUID():undefined;o.label=false;o.exceptions.push({id:crypto.randomUUID(),type:'RELABEL REQUIRED',open:true,at:stamp()});const linked={...old,status:'LINKED',linkedThl:o.id,custody:false,revision:old.revision+1};const marker=crypto.randomUUID();linked.lastMutation=marker;const result=await env.DB.batch([q(env,'UPDATE laundry_orders SET status=?,data=?,revision=revision+1 WHERE id=? AND revision=?','LINKED',J(linked),old.id,old.revision),q(env,"INSERT INTO laundry_orders SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM laundry_orders WHERE id=? AND json_extract(data,'$.lastMutation')=?)",o.id,o.room.id,await hash(secret),'link:'+old.id,1,o.status,o.createdAt,J(o),old.id,marker),q(env,"INSERT INTO laundry_proofs SELECT ?,?,object_key,mime,capture,actor,created_at FROM laundry_proofs WHERE id=? AND EXISTS(SELECT 1 FROM laundry_orders WHERE id=? AND json_extract(data,'$.lastMutation')=?)",o.intakeProof||crypto.randomUUID(),o.id,old.intakeProof||'',old.id,marker)]);need(result[0].meta.changes===1,'INT sudah ditautkan petugas lain.',409);await audit(env,old.id,m,'LINK INT',{thl:o.id,proof:p.proofId,reason:p.reason});return json({order:safe(o),trackingPath:'/checkin#order='+o.id+'&key='+secret});}
 if(path==='/api/laundry/action'||path==='/api/portal/action'){if(publicPath)m=await customerActor(req,env,p.id);const old=await getOrder(env,p.id);const replay=await first(env,'SELECT * FROM laundry_mutations WHERE id=?',m.id+':'+p.mutationId);if(replay){need(replay.hash===await hash(J(p))&&replay.order_id===p.id,'Kunci pengiriman berbeda.',409);return json({order:publicPath?customerView(old):safe(old)});}const proofs=(await q(env,'SELECT * FROM laundry_proofs WHERE order_id=?',old.id).all()).results;try{if(p.action==='refund-account'){const posted=await first(env,"SELECT id FROM finance_transactions WHERE source_key=? AND status IN ('Tercatat','Direversal')",'portal:'+old.id+':refund-'+(Number(p.paymentIndex)+1));need(!posted,'Refund telah dibukukan; gunakan koreksi keuangan.');}if(p.action==='assign'){const pic=await first(env,'SELECT status,role FROM members WHERE id=?',p.assignedTo);need(pic?.status==='Aktif'&&['Owner','Operator'].includes(pic.role),'PIC harus petugas aktif.');}if(m.role==='Finance')need(['review-sop','refund-account','payment-proof','verify-pay','submit-set','approve-set','refund-pay','refund-reconcile','notify-retry'].includes(p.action),'Finance tidak dapat mengubah alur barang.',403);const o=transition(old,p.action,p,m,proofs);const saved=await mutate(env,old,o,m,p);return json({order:publicPath?customerView(saved):safe(saved)});}catch(e){await audit(env,old.id,m,'DENIED '+clean(p.action),{reason:e.message});throw e;}}
 if(path==='/api/laundry/machine'){await audit(env,'MACHINE',m,'MACHINE ATTEMPT',{batch:clean(p.batch),empty:!p.orderIds?.length});need(clean(p.batch),'Nomor batch wajib.');need(Array.isArray(p.orderIds)&&p.orderIds.length>0,'Batch kosong ditolak.');throw new LaundryError('Pindai THL dari detail order untuk memulai setiap batch.');}
 throw new LaundryError('Endpoint tidak tersedia.',404);
}
