// Financial proposals, never automatic posting. Unique keys make detection repeatable.
import F from '../dist/finance-core.js';
export async function importLaundryFinance(env,w,m){const rows=(await env.DB.prepare("SELECT data FROM laundry_orders WHERE json_extract(data,'$.simulation')=0 AND ((status='COMPLETED' AND NOT EXISTS(SELECT 1 FROM finance_transactions f WHERE f.source_key='portal:'||laundry_orders.id||':service')) OR EXISTS(SELECT 1 FROM json_each(laundry_orders.data,'$.pay.attempts') a WHERE json_extract(a.value,'$.received')>0 AND NOT EXISTS(SELECT 1 FROM finance_transactions f WHERE f.source_key='portal:'||laundry_orders.id||':'||json_extract(a.value,'$.id'))) OR (json_extract(data,'$.set.status')='MATCHED' AND json_extract(data,'$.pay.method')='Cash' AND NOT EXISTS(SELECT 1 FROM finance_transactions f WHERE f.source_key='portal:'||laundry_orders.id||':settlement'))) ORDER BY created_at LIMIT 100").all()).results;let added=0;
 for(const row of rows){const o=JSON.parse(row.data),customer='portal:'+o.id,base={sourceType:'portal',unit:'laundry',customer,customerName:o.customer.name,orderId:o.id,createdBy:m.id,createdAt:new Date().toISOString(),status:'Diajukan',fixture:false};const candidates=[];
 if(o.status==='COMPLETED'&&o.handoverProof)candidates.push({suffix:'service',kind:'service',date:F.dateOf(o.handover.at,'Asia/Jakarta'),description:o.id+' · '+o.price.service.name,amount:o.price.total,account:'4101',proof:o.handoverProof});
 for(const a of o.pay.attempts.filter(a=>a.received))candidates.push({suffix:a.id,kind:'receipt',date:F.dateOf(a.receivedAt,'Asia/Jakarta'),description:'Penerimaan '+o.id,amount:a.received,method:a.method,cashAccount:a.method==='Cash'?'1101':'1102',reference:a.reference||o.pay.receiptNo||a.id,proof:a.proof});
 if(o.set.status==='MATCHED'&&o.pay.method==='Cash')candidates.push({suffix:'settlement',kind:'transfer',date:F.dateOf(o.set.approvedAt,'Asia/Jakarta'),description:'Setoran '+o.set.id,amount:o.set.actual,cashAccount:'1101',toAccount:'1102',reference:o.set.reference,proof:o.set.proof});
 for(const c of candidates){const key='portal:'+o.id+':'+c.suffix;if(w.finance.transactions.some(t=>t.sourceKey===key))continue;const proof=await env.DB.prepare('SELECT * FROM laundry_proofs WHERE id=?').bind(c.proof||'').first();const t={...base,...c,id:'PORTAL-'+c.suffix+'-'+o.id,sourceKey:key,portalManaged:true};delete t.proof;delete t.suffix;w.finance.transactions.push(t);if(proof)w.finance.attachments.push({id:'PORTAL-PROOF-'+t.id,objectId:t.id,key:proof.object_key,name:'Bukti-'+o.id+'.'+(proof.mime==='application/pdf'?'pdf':proof.mime==='image/png'?'png':'jpg'),mime:proof.mime,size:0,hash:'',createdBy:proof.actor,createdAt:proof.created_at,version:1});added++;}
 }
 return added;
}
