import {proxySupabase} from './supabase-proxy.mjs';
import {migrationExport} from './migration-export.mjs';
import {laundryDemoRoute} from './laundry-demo-api.mjs';
import { resolveStaffIdentity,staffAuthRoute } from './staff-auth.mjs';
import { importLaundryFinance } from './laundry-finance.mjs';
import { laundryRoute } from './laundry-api.mjs';
import F from '../dist/finance-core.js';
import TH from '../dist/logic.js';
import Services from '../dist/services-core.js';
import assets from '../.sites-runtime/assets.json';
import { emptyWorkspace } from './empty-workspace.mjs';
import { resetBusiness } from './reset-business.mjs';
const J=JSON.stringify,parse=JSON.parse,now=()=>new Date().toISOString(),id=()=>crypto.randomUUID(),eq=(a,b)=>J(a)===J(b);
const json=(v,status=200)=>new Response(J(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
class AppError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const assert=(c,m,s=400)=>{if(!c)throw new AppError(m,s)};
const stmt=(env,sql,...params)=>env.DB.prepare(sql).bind(...params);
const run=(env,sql,...params)=>stmt(env,sql,...params).run();
const first=(env,sql,...params)=>stmt(env,sql,...params).first();
async function identity(req,env){const user=await resolveStaffIdentity(req,env);assert(user,'Silakan masuk untuk membuka ruang kerja.',401);return user;}
const owner=m=>assert(m.role==='Owner'&&m.status==='Aktif','Tindakan memerlukan Owner aktif.',403);
const financeMember=m=>assert(['Owner','Finance','Operator'].includes(m.role)&&m.status==='Aktif','Akses keuangan belum diberikan.',403);
const reviewer=m=>assert(['Owner','Finance'].includes(m.role)&&m.status==='Aktif','Tindakan memerlukan Owner atau Finance.',403);
async function state(env){const row=await first(env,'SELECT revision,data FROM workspace WHERE id=?','main');return row?{revision:row.revision,...parse(row.data)}:null;}
async function bootstrap(env,user){let w=await state(env);if(!w){assert(env.ALLOW_INITIAL_OWNER==='1','Ruang kerja belum diinisialisasi oleh pemilik.',503);const value=emptyWorkspace(user.id);await run(env,'INSERT OR IGNORE INTO workspace(id,revision,data,updated_at) VALUES(?,?,?,?)','main',0,J(value),now());w=await state(env);}
 if(w.operations.settings.serviceCatalogVersion!==Services.VERSION){const migrated=F.clone(w);Services.install(migrated.operations);const {revision,...data}=migrated;const result=await run(env,'UPDATE workspace SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',J(data),now(),'main',w.revision);w=await state(env);assert(w.operations.settings.serviceCatalogVersion===Services.VERSION,'Daftar layanan sedang diperbarui. Muat ulang halaman.',409);}
 let m=await first(env,'SELECT * FROM members WHERE id=?',user.id);if(!m){await run(env,'INSERT OR IGNORE INTO members(id,name,email,role,status,profile,created_at) VALUES(?,?,?,?,?,?,?)',user.id,user.name,user.email,w.ownerId===user.id?'Owner':'Operator',w.ownerId===user.id?'Aktif':'Menunggu','{}',now());m=await first(env,'SELECT * FROM members WHERE id=?',user.id);}return {w,m};}
function project(w,m){let operations=F.clone(w.operations),finance=F.clone(w.finance);if(m.role==='Konsumen'){const p=parse(m.profile||'{}'),c=p.customerId&&operations.tenants.some(t=>t.id===p.customerId)?p.customerId:null;operations.orders=operations.orders.filter(o=>!!c&&o.tenantId===c);operations.tenants=operations.tenants.filter(t=>t.id===c);operations.invoices=operations.invoices.filter(i=>!!c&&i.tenantId===c);operations.requests=operations.requests.filter(r=>!!c&&r.tenantId===c);operations.reports=[];operations.evaluations=[];operations.settlements=[];operations.audit=[];operations.employees=[];operations.settings={...operations.settings,labelNext:0,labelEnd:0,receiptNext:0,receiptEnd:0,checklist:{}};finance=null;}else if(m.role==='Finance'){operations.evaluations=[];operations.reports=[];}else if(m.role==='Operator'){finance.journals=[];finance.bankRows=[];finance.snapshots=[];finance.budgets=[];finance.periods=[];finance.audit=[];finance.transactions=finance.transactions.filter(t=>t.createdBy===m.id||t.sourceType==='laundry'&&t.status!=='Tercatat');const ids=new Set(finance.transactions.map(t=>t.id));finance.attachments=finance.attachments.filter(a=>ids.has(a.objectId));operations.evaluations=operations.evaluations.filter(e=>e.employeeId===parse(m.profile||'{}').employeeId);}return {revision:w.revision,operations,finance,member:{...m,profile:parse(m.profile||'{}')},clock:F.today(),serverTime:now(),scheduleMode:'on-access',maintenance:w.maintenance||null,readiness:w.readiness||{}};}
async function save(env,w,old,m,action,objectId,mutation){const token=id(),at=now(),before=old.finance,after=w.finance;after.audit=after.audit||[];if(after.journals.length!==before.journals.length)for(const snap of after.snapshots.filter(x=>x.status==='Final')){const current=F.report(after,snap.filter).balanceJournals.map(j=>j.id);if(!eq(snap.journalIds,current))snap.superseded=true;}const audit={id:id(),actor:m.id,actorName:m.name,at,action,objectId,before:objectId?(before.transactions.find(t=>t.id===objectId)||null):null,after:objectId?(after.transactions.find(t=>t.id===objectId)||null):null};after.audit.unshift(audit);const value={ownerId:w.ownerId,operations:w.operations,finance:after,projectionsReady:true,maintenance:w.maintenance||null,readiness:w.readiness||{}};const guard='EXISTS (SELECT 1 FROM workspace WHERE id=\'main\' AND updated_at=?)';const q=[stmt(env,'UPDATE workspace SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',J(value),token,'main',old.revision)];
 const txOld=new Map((old.projectionsReady?before.transactions:[]).map(t=>[t.id,t]));for(const t of after.transactions)if(!eq(t,txOld.get(t.id)))q.push(stmt(env,`INSERT INTO finance_transactions(id,source_key,kind,unit,customer,date,status,created_by,data) SELECT ?,?,?,?,?,?,?,?,? WHERE ${guard} ON CONFLICT(id) DO UPDATE SET status=excluded.status,data=excluded.data,date=excluded.date,source_key=excluded.source_key,kind=excluded.kind,unit=excluded.unit,customer=excluded.customer`,t.id,t.sourceKey,t.kind,t.unit,t.customer||'',t.date,t.status,t.createdBy,J(t),token));
 const js=new Set((old.projectionsReady?before.journals:[]).map(j=>j.id));for(const j of after.journals)if(!js.has(j.id)){q.push(stmt(env,`INSERT INTO journals(id,transaction_id,date,unit,data) SELECT ?,?,?,?,? WHERE ${guard}`,j.id,j.transactionId,j.date,j.unit,J(j),token));for(let n=0;n<j.lines.length;n++){const l=j.lines[n];q.push(stmt(env,`INSERT INTO journal_lines(id,journal_id,account,date,unit,customer,debit,credit,cash_category) SELECT ?,?,?,?,?,?,?,?,? WHERE ${guard}`,j.id+':'+n,j.id,l.account,j.date,l.unit||j.unit,l.customer||j.customer||'',l.debit,l.credit,l.cashCategory,token));}}
 const proofIds=new Set(before.attachments.map(a=>a.id));for(const a of after.attachments)if(!proofIds.has(a.id))q.push(stmt(env,`INSERT INTO attachments(id,object_id,object_key,name,mime,size,hash,created_by,created_at,version) SELECT ?,?,?,?,?,?,?,?,?,? WHERE ${guard}`,a.id,a.objectId,a.key,a.name,a.mime,a.size,a.hash,a.createdBy,a.createdAt,a.version,token));
 for(const kind of ['policies','periods','bankRows','snapshots','budgets','insights'])if(!eq(before[kind],after[kind]))q.push(stmt(env,`INSERT INTO finance_records(id,kind,date,data) SELECT ?,?,?,? WHERE ${guard} ON CONFLICT(id) DO UPDATE SET data=excluded.data,date=excluded.date`,kind,kind,at.slice(0,10),J(after[kind]),token));
 if(w.memberChange){const p=w.memberChange;q.push(stmt(env,`UPDATE members SET role=?,status=?,profile=? WHERE id=? AND ${guard}`,p.role,p.status,J({employeeId:p.employeeId||'',customerId:p.customerId||''}),p.id,token));}
 q.push(stmt(env,`INSERT INTO finance_audit(id,actor,at,action,object_id,data) SELECT ?,?,?,?,?,? WHERE ${guard}`,audit.id,m.id,at,action,objectId||'',J(audit),token));
 if(mutation)q.push(stmt(env,`INSERT INTO mutations(id,actor,created_at,result) SELECT ?,?,?,? WHERE ${guard}`,mutation,m.id,at,J({objectId,requestHash:w.requestHash}),token));
 const result=await env.DB.batch(q);assert(result[0].meta.changes===1,'Data telah berubah di sesi lain. Muat ulang, lalu kirim kembali; input Anda tetap tersedia.',409);w.revision=old.revision+1;return project(w,m);}
async function payload(req){assert(Number(req.headers.get('Content-Length')||0)<8000000,'Data terlalu besar.');try{return await req.json()}catch{throw new AppError('Format data tidak valid.')}}
function filter(v){const f={start:String(v.start||''),end:String(v.end||''),unit:String(v.unit||''),customer:String(v.customer||''),source:String(v.source||'')};assert(F.dateValid(f.start)&&F.dateValid(f.end)&&f.start<=f.end,'Rentang tanggal tidak valid.');assert(f.end<=F.day(f.start,3660),'Pilih rentang maksimal 10 tahun.');return f;}
function proof(s,t){return s.attachments.some(a=>a.objectId===t.id)}
function approveTransaction(w,t,m){reviewer(m);if(t.kind==='receipt'){for(const al of t.allocations?.length?t.allocations:[{orderId:t.orderId}]){const source=w.operations.orders.find(o=>o.id===al.orderId),inv=w.operations.invoices.find(i=>i.id===al.orderId);if(source)assert(t.customer===(source.customerId||source.tenantId||'customer-'+source.id)&&t.unit==='laundry','Alokasi harus milik pelanggan dan unit yang sama.');if(inv)assert(t.customer===inv.tenantId&&t.unit==='hunian','Alokasi invoice harus milik pelanggan dan unit yang sama.');}const o=w.operations.orders.find(o=>o.id===t.orderId),invoice=w.operations.invoices.find(i=>i.id===t.orderId);if(o){assert(t.customer===(o.customerId||o.tenantId||'customer-'+o.id)&&t.unit==='laundry','Pelanggan atau unit tidak cocok dengan order.');t.sourceType='laundry';}if(invoice){assert(t.customer===invoice.tenantId&&t.unit==='hunian','Pelanggan atau unit tidak cocok dengan invoice.');t.sourceType='hunian';}}assert(t.status!=='Direversal','Jurnal telah direversal.');assert(proof(w.finance,t)||t.systemGenerated,'Lampirkan file bukti transaksi terlebih dahulu.');assert(!t.holdReason,'Selesaikan alasan tertahan sebelum mencatat transaksi.');if(t.status==='Tercatat'){assert(t.createdBy!==m.id,'Pemeriksa harus akun orang lain dari pembuat transaksi.');t.reviewedBy=m.id;t.reviewedAt=now();return;}
 assert(t.date<=F.today(w.finance.policies.timezone)||t.fixture,'Transaksi masa depan belum boleh dicatat.');if(t.method==='QRIS'||t.method==='Transfer')assert(t.verifiedReference?.trim().length>=3,'Masukkan referensi mutasi/merchant independen sebelum verifikasi.');if(t.kind==='receipt'&&t.method==='Cash'){const config=w.operations.settings;assert(config.receiptNext<=config.receiptEnd,'Rentang kuitansi habis. Minta Owner menambah rentang.');t.receiptNo='CSH-'+String(config.receiptNext++).padStart(6,'0');}F.post(w.finance,t);t.postedAt=now();t.postedBy=m.id;if(t.createdBy!==m.id){t.reviewedBy=m.id;t.reviewedAt=now();}}
function scan(w,m){let n=0;for(const t of F.candidates(w.operations,w.finance,m.id)){w.finance.transactions.push(t);n++;}return n;}
function gate(s,ops,f){const r=F.report(s,f);assert(!f.customer&&!f.source,'Neraca dan paket formal harus mencakup seluruh pelanggan dan sumber transaksi.');const issues=F.alerts(s,ops,f).filter(a=>a.severity!=='info'&&(a.severity==='critical'||['D01','D02','D04','D08','D09','D10'].includes(a.rule)));assert(!issues.length,'Belum dapat Final: '+issues.slice(0,3).map(a=>a.title).join('; '));assert(s.policies.approved&&s.policies.openingApproved,'Sahkan kebijakan dan saldo awal terlebih dahulu.');assert(!r.balanceDifference&&!r.cashDifference,'Neraca atau arus kas belum cocok.');for(const t of s.transactions.filter(t=>t.status==='Tercatat'&&!t.fixture&&t.date<=f.end&&(!f.unit||t.unit===f.unit))){const j=s.journals.find(j=>j.transactionId===t.id);if(j?.lines.some(l=>l.account==='1102')&&t.kind!=='opening')assert(s.bankRows.some(row=>row.matchedId===t.id),'Mutasi bank belum dicocokkan: '+t.id);if(t.kind==='receipt'&&t.method==='Cash')assert(ops.settlements.some(st=>st.paymentIds?.includes(t.id)&&st.status==='Terverifikasi Owner'&&!st.difference),'Cash penerimaan belum selesai closing/settlement: '+t.id);}return r;}
function snapshot(s,ops,f,m,mode='Draft',label='Manual'){const r=mode==='Final'?gate(s,ops,f):F.report(s,f);const entry={completeness:s.policies.openingApproved&&s.journals.some(j=>j.date<=f.start)?'Tersedia':'Belum lengkap',id:'RPT-'+id(),filter:f,status:mode,label,createdAt:now(),createdBy:m.id,createdName:m.name,revision:1,totals:{revenue:r.revenue,profit:r.profit,assets:r.assets,liabilities:r.liabilities,equity:r.equity,cashOpening:r.cashOpening,cashEnd:r.cashEnd,cashChange:r.cashChange},report:r,policies:F.clone(s.policies),journalIds:r.balanceJournals.map(j=>j.id)};s.snapshots.unshift(entry);return entry;}
function catchup(w,m){const s=w.finance,dt=F.today(s.policies.timezone),last=s.lastAutoDate||F.day(dt,-1);if(s.startedOn&&(!s.policies.approved||!s.transactions.length))return false;let changed=false;const start=last<F.day(dt,-366)?F.day(dt,-366):last;for(const p of F.periodsBetween(start,F.day(dt,-1))){const key='Harian otomatis '+p.start;if(!s.snapshots.some(x=>x.label===key)){snapshot(s,w.operations,{...p,unit:'',customer:'',source:''},m,'Draft',key);changed=true;}}const prevEnd=F.day(dt.slice(0,7)+'-01',-1),prevStart=prevEnd.slice(0,7)+'-01',label='Bulanan otomatis '+prevStart.slice(0,7);if((!s.startedOn||prevEnd>=s.startedOn)&&!s.snapshots.some(x=>x.label===label)){snapshot(s,w.operations,{start:prevStart,end:prevEnd,unit:'',customer:'',source:''},m,'Draft',label);changed=true;}if(changed)s.lastAutoDate=dt;return changed;}
export async function runScheduled(env){if(env.TOP_HILLS_MIGRATION_MODE==='export')return {created:false};if(env.DATA_BACKEND==='supabase'){const r=await proxySupabase(new Request('https://top-hills-co-journal.atikadewi.chatgpt.site/api/__backend/scheduled',{method:'POST'}),env,'/api/__backend/scheduled');if(!r.ok)throw new Error('Supabase schedule unavailable');return r.json();}const w=await state(env);if(!w)return {created:false};const old=F.clone(w),m={id:'system-draft-generator',name:'Generator Draft',role:'Finance',status:'Aktif',profile:'{}'};if(!catchup(w,m))return {created:false};await save(env,w,old,m,'Generator Draft terjadwal','');return {created:true};}
function validateOps(next,old,m,s){assert(next&&Array.isArray(next.orders)&&Array.isArray(next.invoices),'Data operasional tidak lengkap.');assert(J(next).length<4000000,'Data operasional terlalu besar.');if(m.role==='Operator')assert(old.employees.some(e=>e.id===parse(m.profile||'{}').employeeId&&e.active),'Akun Operator belum ditautkan ke karyawan aktif.',403);assert(next.settings&&Array.isArray(next.settings.packages)&&next.settings.packages.every(p=>Services.valid(p)),'Paket layanan tidak valid.');for(const o of next.orders)assert(next.employees.some(e=>e.id===o.pic),'PIC order tidak ditemukan.');
for(const t of next.tenants){const prior=old.tenants.find(x=>x.id===t.id);if(eq(t,prior))continue;assert(['Kost putri','Penginapan'].includes(t.type),'Jenis hunian tidak valid.');for(const k of ['name','contact','building','floor','room','roomType'])assert(typeof t[k]==='string'&&t[k].trim().length>0&&t[k].length<=160,'Lengkapi '+k+' pelanggan.');assert(['Aktif','Check-out','Arsip'].includes(t.status),'Status pelanggan tidak valid.');assert(!t.start||F.dateValid(t.start),'Tanggal mulai tidak valid.');assert(!t.end||F.dateValid(t.end),'Tanggal akhir tidak valid.');assert(!t.start||!t.end||t.start<=t.end,'Periode tinggal tidak valid.');assert(!t.checkout||Number.isFinite(Date.parse(t.checkout)),'Checkout tidak valid.');assert(t.type!=='Penginapan'||t.checkout,'Checkout penginapan wajib diisi.');assert(Number.isFinite(t.rent)&&t.rent>=0,'Nilai sewa tidak valid.');if(prior&&t.status!=='Aktif')assert(!next.orders.some(o=>o.tenantId===t.id&&!['Selesai','Dibatalkan'].includes(o.stage)),'Selesaikan laundry pelanggan sebelum checkout/arsip.');}
for(const o of next.orders){assert(!o.tenantId||next.tenants.some(t=>t.id===o.tenantId),'Pelanggan order tidak ditemukan.');if(!old.orders.some(x=>x.id===o.id)){assert(typeof o.customer==='string'&&o.customer.trim()&&typeof o.contact==='string'&&o.contact.trim(),'Nama dan kontak pelanggan wajib diisi.');if(o.type!=='Umum'){for(const k of ['building','floor','room','roomType'])assert(typeof o[k]==='string'&&o[k].trim(),'Lengkapi lokasi pelanggan.');}assert(Number.isFinite(Date.parse(o.due)),'Target selesai tidak valid.');assert(o.type!=='Penginapan'||o.checkout&&Number.isFinite(Date.parse(o.checkout)),'Checkout penginapan wajib diisi.');assert(!o.checkout||Date.parse(o.due)<=Date.parse(o.checkout)||o.evidence?.checkoutApproval,'Target melewati checkout tanpa persetujuan alternatif.');}}
for(const k of ['orders','invoices','reports','evaluations','settlements','requests','tenants','employees']){assert(Array.isArray(next[k]),'Daftar '+k+' tidak valid.');assert(new Set(next[k].map(x=>x.id)).size===next[k].length,'ID '+k+' berulang.');for(const x of old[k])assert(next[k].some(y=>y.id===x.id),'Riwayat tidak dapat dihapus. Nonaktifkan atau buat koreksi.');}
if(m.role!=='Owner'){for(const k of ['employees','evaluations'])assert(eq(next[k],old[k]),'Perubahan '+k+' memerlukan Owner.',403);const a=F.clone(next.settings),b=F.clone(old.settings);delete a.checklist;delete b.checklist;for(const k of ['labelNext','receiptNext']){assert(Number.isInteger(a[k])&&a[k]>=b[k],'Rentang nomor tidak dapat diturunkan.',403);a[k]=b[k];}assert(eq(a,b),'Kebijakan hanya dapat diubah Owner.',403);const employee=parse(m.profile||'{}').employeeId;for(const r of next.reports){const prior=old.reports.find(x=>x.id===r.id);if(!eq(r,prior)){assert(r.employeeId===employee,'Hanya laporan aktivitas Anda yang dapat diubah.',403);if(prior)assert(eq(r.feedback,prior.feedback)&&eq(r.reviewedAt,prior.reviewedAt),'Feedback memerlukan Owner.',403);}}}
for(const t of s.transactions.filter(t=>t.sourceType==='laundry'&&(t.kind==='service'||['Tercatat','Direversal'].includes(t.status)))){const a=old.orders.find(o=>o.id===t.orderId),b=next.orders.find(o=>o.id===t.orderId);if(a)for(const k of ['total','quantity','billedQuantity','customer','customerId','tenantId','completed'])assert(eq(a[k],b[k]),'Order sudah terhubung ke Laporan. Nilai layanan dikunci agar order dan laporan tetap cocok.');}
for(const o of next.orders){try{Services.validateOrder(o,old.orders.find(x=>x.id===o.id),next.settings.packages,m.role);}catch(e){throw new AppError(e.message);}assert(Number.isSafeInteger(o.total)&&o.total>=0,'Total order harus rupiah bulat.');const a=old.orders.find(x=>x.id===o.id);if(a){assert(eq(a.financePayments,o.financePayments),'Pembayaran dicatat melalui Transaksi & bukti.');if(m.role!=='Owner')for(const k of ['payment','paidAt','paymentRef','method','ownerVerifiedAt','settlementId'])assert(eq(a[k],o[k]),'Pembayaran dan verifikasi menggunakan menu keuangan.',403);}else assert(!o.financePayments?.length&&!o.paidAt&&!o.payment?.startsWith('Lunas'),'Order baru belum mempunyai pembayaran terverifikasi.');if(o.stage==='Selesai')assert(o.completed&&o.evidence?.handover&&o.evidence?.customerAck,'Penyelesaian memerlukan bukti serah terima.');}
if(m.role!=='Owner'){for(const i of next.invoices){const prior=old.invoices.find(x=>x.id===i.id);if(prior)assert(eq(i.history,prior.history)&&i.paid===prior.paid,'Penerimaan invoice menggunakan menu keuangan.',403);else assert(i.paid===0&&!i.history?.length,'Tagihan baru belum dibayar.');}for(const st of next.settlements||[]){const prior=old.settlements.find(x=>x.id===st.id);if(prior){for(const k of ['status','resolved','bankReference','verifiedBy'])if(st.status==='Terverifikasi Owner'||st.resolved)assert(eq(st[k],prior[k]),'Verifikasi setoran memerlukan Owner.',403);}else assert(st.status!=='Terverifikasi Owner'&&!st.resolved,'Setoran baru belum dapat terverifikasi.',403);}}
}
function syncPayment(w,t){if(t.status!=='Tercatat'||t.kind!=='receipt')return;for(const al of t.allocations?.length?t.allocations:[{orderId:t.orderId,amount:t.amount}]){const o=w.operations.orders.find(o=>o.id===al.orderId);if(o&&!o.financeFixture){o.financePayments=o.financePayments||[];const p={id:t.id,amount:al.amount,date:t.date,receivedAt:t.occurredAt||null,recordedAt:t.postedAt||now(),method:t.method,status:t.method==='Cash'?'Lunas Cash':'Terverifikasi',reference:t.reference,verifiedBy:t.postedBy};const ix=o.financePayments.findIndex(p=>p.id===t.id);if(ix<0)o.financePayments.push(p);else o.financePayments[ix]=p;const sum=o.financePayments.reduce((n,p)=>n+p.amount,0);o.payment=sum>=o.total?(t.method==='Cash'?'Lunas Cash':'Lunas Terverifikasi'):'Dibayar sebagian';o.method=t.method;o.paidAt=o.financePayments[0].receivedAt;o.paymentRef=t.reference;if(t.receiptNo)o.receipt=t.receiptNo;t.sourceKey='laundry:'+o.id+':payment:'+t.id;t.sourceType='laundry';}const inv=w.operations.invoices.find(i=>i.id===al.orderId);if(inv){inv.history=inv.history||[];if(inv.openingPaid===undefined)inv.openingPaid=Math.max(0,inv.paid-inv.history.reduce((n,p)=>n+p.amount,0));if(!inv.history.some(p=>p.id===t.id))inv.history.push({id:t.id,amount:al.amount,date:t.date,method:t.method,reference:t.reference,at:now(),verified:true,actor:t.postedBy});inv.paid=inv.openingPaid+inv.history.reduce((n,p)=>n+p.amount,0);t.sourceType='hunian';t.sourceKey='invoice:'+inv.id+':payment:'+t.id;}}}

async function requestHash(p){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(J(p))))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function replayResult(env,p,w,m){if(!p.mutationId)return null;assert(typeof p.mutationId==='string'&&p.mutationId.length<=100,'Kunci transaksi tidak valid.');const previous=await first(env,'SELECT actor,result FROM mutations WHERE id=?',p.mutationId);if(!previous)return null;const result=parse(previous.result);assert(previous.actor===m.id&&result.requestHash===w.requestHash,'Kunci transaksi telah digunakan untuk isi berbeda.',409);return {...project(w,m),objectId:result.objectId};}
function stampOperations(next,old){const at=now();for(const o of next.orders){const prior=old.orders.find(x=>x.id===o.id);if(!prior)o.created=at;else assert(o.created===prior.created,'Waktu penerimaan tidak dapat ditimpa.');if(o.completed&&!prior?.completed)o.completed=at;if(o.handoverAt&&!prior?.handoverAt)o.handoverAt=at;const ids=new Set((prior?.history||[]).map(h=>J(h)));for(const h of o.history||[])if(!ids.has(J(h)))h.at=at;}for(const r of next.reports){const prior=old.reports.find(x=>x.id===r.id);if(!eq(r,prior))r.submittedAt=at;}for(const a of next.audit)if(!old.audit.some(x=>x.id===a.id))a.at=at;}

function publicAsset(path,req){const a=assets[path==='/'?'/index.html':path];if(!a)return new Response('Halaman tidak ditemukan',{status:404});const cache=path.endsWith('.html')||path==='/'?'no-store':'public, max-age=0, must-revalidate';const etag='"'+(a.etag||'')+'"';if(a.etag&&req?.headers.get('If-None-Match')===etag&&cache!=='no-store')return new Response(null,{status:304,headers:{ETag:etag,'Cache-Control':cache}});const bytes=Uint8Array.from(atob(a.data),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':a.mime,'Cache-Control':cache,'ETag':etag,'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; object-src 'none'; frame-src 'self' blob:; base-uri 'self'; form-action 'self'"}});}
export async function route(req,env){const u=new URL(req.url),path=u.pathname;if(path==='/api/maintenance/export')return migrationExport(req,env);if(env.TOP_HILLS_MIGRATION_MODE==='export'&&path.startsWith('/api/'))return json({error:'Data sedang dipindahkan. Silakan kembali sebentar lagi.'},503);if(env.DATA_BACKEND==='supabase'&&path.startsWith('/api/'))return proxySupabase(req,env);if(path.startsWith('/api/laundry-demo/'))return laundryDemoRoute(req,env);if(path.startsWith('/api/auth/'))return staffAuthRoute(req,env);if(path.startsWith('/api/portal/')||path.startsWith('/api/laundry/'))return laundryRoute(req,env);if(!path.startsWith('/api/'))return publicAsset(path==='/demo'?'/demo.html':path==='/sop-coverage'?'/sop-coverage.html':path==='/login'?'/staff-login.html':path==='/checkin'?'/portal.html':path==='/laundry-desk'?'/laundry-desk.html':path,req);assert(env.DB&&env.BUCKET,'Penyimpanan belum tersedia. Coba kembali sesaat lagi.',503);if(path==='/api/maintenance/reset')return resetBusiness(req,env);const user=await identity(req,env);if(req.method!=='GET'){assert(req.headers.get('Origin')===u.origin,'Permintaan harus berasal dari website ini.',403);assert(req.headers.get('X-Top-Hills')==='1','Permintaan tidak valid.',403);}
 const {w,m}=await bootstrap(env,user);assert(m.status==='Aktif','Akun Anda menunggu akses dari Owner.',403);assert(w.maintenance?.phase!=='purging','Reset sedang menyelesaikan pembersihan bukti. Coba lagi sebentar.',503);const old=F.clone(w),s=w.finance;
 if(path==='/api/state'&&req.method==='GET'){if(['Owner','Finance'].includes(m.role)&&await importLaundryFinance(env,w,m))return json(await save(env,w,old,m,'Deteksi order portal ke usulan laporan',''));if(['Owner','Finance'].includes(m.role)&&catchup(w,m))return json(await save(env,w,old,m,'Laporan otomatis saat dibuka',''));return json(project(w,m));}
 if(path==='/api/sync'&&req.method==='GET')return json({revision:w.revision,member:{id:m.id,role:m.role,status:m.status,profile:parse(m.profile||'{}')},serverTime:now()});
 if(path==='/api/readiness'&&req.method==='GET'){owner(m);return json({database:env.DATA_BACKEND==='postgres'?'Supabase PostgreSQL':'D1',databaseConnected:true,proofStorage:env.DATA_BACKEND==='postgres'?'Supabase Storage':'R2',proofStorageAvailable:!!env.BUCKET,members:(await stmt(env,'SELECT id,role,status,profile FROM members').all()).results,reviewed:w.readiness||{},reset:w.maintenance||null,supabaseConnected:env.DATA_BACKEND==='postgres',scheduleMode:'on-access'});}
 if(path==='/api/members'&&req.method==='GET'){owner(m);return json((await stmt(env,'SELECT id,name,email,role,status,profile FROM members').all()).results);}
 if(path.startsWith('/api/proof/')&&req.method==='GET'){financeMember(m);const a=s.attachments.find(a=>a.id===decodeURIComponent(path.split('/').pop()));assert(a,'Bukti tidak ditemukan.',404);if(m.role==='Operator')assert(a.createdBy===m.id||s.transactions.some(t=>t.id===a.objectId&&t.createdBy===m.id),'Bukti tidak tersedia untuk akun ini.',403);if(a.fixture)return publicAsset('/assets/Bukti-latihan-Top-Hills.pdf');const b=await env.BUCKET.get(a.key);assert(b,'File bukti tidak tersedia.',404);return new Response(b.body,{headers:{'Content-Type':a.mime,'Content-Disposition':`inline; filename="${a.name.replace(/[^a-zA-Z0-9. _-]/g,'_')}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}
 if(m.role==='Konsumen'&&path==='/api/operations'){const p=await payload(req);w.requestHash=await requestHash({...p,path});const replay=await replayResult(env,p,w,m);if(replay)return json(replay);assert(p.revision===w.revision,'Data telah berubah. Muat ulang.',409);const next=p.operations,own=parse(m.profile||'{}').customerId;assert(own&&w.operations.tenants.some(t=>t.id===own),'Akun belum terkait penghuni.',403);const prior=project(w,m).operations;assert(Array.isArray(next.orders)&&next.orders.length===prior.orders.length&&Array.isArray(next.requests),'Data pelanggan tidak valid.',403);for(const r of prior.requests)assert(eq(r,next.requests.find(x=>x.id===r.id)),'Permintaan yang sudah dikirim tidak dapat ditimpa.',403);for(const key of Object.keys(prior))if(!['orders','requests','audit'].includes(key))assert(eq(next[key],prior[key]),'Perubahan tidak diizinkan.',403);for(const o of next.orders){const existing=w.operations.orders.find(x=>x.id===o.id&&x.tenantId===own);assert(existing,'Order tidak tersedia.',403);const normalized=F.clone(o);normalized.evidence.customerAck=existing.evidence.customerAck;normalized.stage=existing.stage;normalized.completed=existing.completed;normalized.history=existing.history;assert(eq(normalized,existing),'Hanya konfirmasi penerimaan yang diizinkan.',403);if(o.evidence.customerAck&&!existing.evidence.customerAck){assert(existing.evidence.handover&&existing.recipient,'Penyerahan belum dicatat.');existing.evidence.customerAck=true;TH.advance(existing,'Selesai',m.name,F.today());}}for(const r of next.requests.filter(x=>!prior.requests.some(z=>z.id===x.id))){assert(r.tenantId===own&&Number.isInteger(r.bags)&&r.bags>0&&r.bags<=26,'Permintaan tidak valid.');w.operations.requests.push({...r,status:'Baru',createdAt:now()});}scan(w,m);return json(await save(env,w,old,m,'Aktivitas pelanggan',own,p.mutationId));}
 financeMember(m);
 if(path==='/api/proof'&&req.method==='POST'){assert(Number(req.headers.get('Content-Length')||0)<=11*1024*1024,'Unggahan melebihi batas.');const form=await req.formData(),file=form.get('file'),objectId=String(form.get('objectId')||''),t=s.transactions.find(t=>t.id===objectId);assert(t,'Simpan draft transaksi sebelum mengunggah bukti.');assert(t.createdBy===m.id||['Owner','Finance'].includes(m.role),'Bukti ini tidak dapat Anda ubah.',403);assert(s.attachments.filter(a=>a.objectId===objectId).length<10,'Maksimal 10 versi/file per transaksi.');assert(file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=10*1024*1024,'Bukti harus JPG, PNG, atau PDF, maksimal 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const type=bytes[0]===0xff&&bytes[1]===0xd8?'image/jpeg':bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10'?'image/png':new TextDecoder().decode(bytes.slice(0,5))==='%PDF-'?'application/pdf':'';assert(type,'Isi file harus JPG, PNG, atau PDF yang valid.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');const reason=String(form.get('reason')||'Unggahan awal');assert(!s.attachments.some(a=>a.objectId===objectId)||reason.length>=5,'Alasan versi baru wajib diisi.');const a={documentDate:String(form.get('documentDate')||t.date),proofType:String(form.get('proofType')||'Dokumen transaksi'),referenceAmount:t.amount||0,reason,id:'ATT-'+id(),objectId,key:'proof/'+id(),name:String(file.name).slice(0,150),mime:type,size:bytes.length,hash,createdBy:m.id,createdAt:now(),version:1+s.attachments.filter(a=>a.objectId===objectId).length};await env.BUCKET.put(a.key,bytes,{httpMetadata:{contentType:type}});s.attachments.push(a);try{return json(await save(env,w,old,m,'Lampirkan versi bukti',objectId))}catch(e){await env.BUCKET.delete(a.key);throw e;}}
 const p=await payload(req);w.requestHash=await requestHash({...p,path});const replay=await replayResult(env,p,w,m);if(replay)return json(replay);assert(p.revision===w.revision,'Data telah berubah. Muat ulang sebelum menyimpan.',409);
 let action='Perbarui laporan',objectId=p.id||'';
 if(path==='/api/operations'){assert(['Owner','Operator'].includes(m.role),'Akses tidak tersedia.',403);if(m.role==='Operator'){assert(eq(p.operations.evaluations,project(w,m).operations.evaluations),'Penilaian hanya dapat diubah Owner.',403);p.operations.evaluations=F.clone(w.operations.evaluations);}validateOps(p.operations,w.operations,m,s);stampOperations(p.operations,w.operations);w.operations=p.operations;scan(w,m);action='Simpan operasional dan deteksi jurnal';}
 else if(path==='/api/transactions'){const input=p.transaction;assert(input&&typeof input==='object','Transaksi tidak valid.');const prior=s.transactions.find(t=>t.id===input.id);if(prior)assert(!prior.portalManaged,'Nilai berasal dari portal; koreksi dari order sumber.');if(prior)assert(!['Tercatat','Direversal'].includes(prior.status),'Transaksi tercatat tidak dapat ditimpa. Gunakan reversal.');if(prior)assert(prior.createdBy===m.id||['Owner','Finance'].includes(m.role),'Transaksi bukan milik Anda.',403);const t={...input,id:prior?.id||'TRX-'+id(),sourceKey:prior?.sourceKey||'manual:'+id(),sourceType:prior?.sourceType||'manual',createdBy:prior?.createdBy||m.id,createdName:prior?.createdName||m.name,createdAt:prior?.createdAt||now(),status:'Draft',fixture:false,systemGenerated:false,reviewedBy:null};F.validateTransaction(t,s);if(t.kind==='receipt'){assert(t.reference?.trim().length>=3,'Referensi penerimaan wajib diisi.');if(t.method==='Cash')assert(!w.operations.orders.find(o=>o.id===t.orderId&&o.mode==='Jemput'&&!o.evidence?.weigh),'Cash jemput awal sebelum timbang tidak diperbolehkan.');}if(prior)s.transactions[s.transactions.indexOf(prior)]=t;else s.transactions.push(t);objectId=t.id;action='Simpan draft transaksi';}
 else if(path==='/api/post'){const t=s.transactions.find(t=>t.id===p.id);assert(t,'Transaksi tidak ditemukan.');if(m.role==='Operator'){assert(['Draft','Diajukan','Tertahan'].includes(t.status),'Transaksi tercatat tidak dapat diajukan ulang.');assert(t.createdBy===m.id,'Transaksi bukan milik Anda.',403);assert(proof(s,t),'Lampirkan bukti terlebih dahulu.');t.status='Diajukan';}else{if(p.verifiedReference)t.verifiedReference=String(p.verifiedReference).slice(0,200);if(p.resolveReason){assert(t.holdReason!=='Kebijakan pengakuan belum disetujui.'||s.policies.approved,'Sahkan kebijakan terlebih dahulu.');if(t.kind==='service'&&t.sourceType==='laundry'){const o=w.operations.orders.find(o=>o.id===t.orderId);assert(o?.evidence?.qc&&(s.policies.recognition!=='handover'||o?.evidence?.handover&&o?.evidence?.customerAck),'Lengkapi bukti penyelesaian pada order terlebih dahulu.');}assert(String(p.resolveReason).length>=5,'Penjelasan penyelesaian minimal 5 karakter.');t.holdReason='';t.resolveReason=p.resolveReason;}approveTransaction(w,t,m);syncPayment(w,t);}action='Periksa dan catat transaksi';}
 else if(path==='/api/scan'){reviewer(m);scan(w,m);await importLaundryFinance(env,w,m);action='Deteksi sumber operasional';}
 else if(path==='/api/reverse'){reviewer(m);const t=s.transactions.find(t=>t.id===p.id);assert(t&&t.status==='Tercatat','Pilih transaksi tercatat.');assert(String(p.reason).length>=5,'Alasan reversal wajib diisi.');assert(!s.transactions.some(x=>x.reversalOf===t.id),'Transaksi sudah mempunyai reversal.');const j=s.journals.find(j=>j.transactionId===t.id);const rev={id:'REV-'+id(),sourceKey:'reversal:'+t.id,kind:'adjustment',sourceType:'manual',date:p.date,unit:t.unit,customer:t.customer,orderId:t.orderId,description:'Reversal '+t.id+': '+p.reason,reason:p.reason,createdBy:m.id,createdAt:now(),status:'Draft',reversalOf:t.id,lines:j.lines.map(l=>({...l,debit:l.credit,credit:l.debit}))};F.post(s,rev);s.transactions.push(rev);t.status='Direversal';for(const a of s.attachments.filter(a=>a.objectId===t.id))s.attachments.push({...a,id:'ATT-'+id(),objectId:rev.id});action='Reversal dengan jurnal pembalik';objectId=rev.id;}
 else if(path==='/api/policies'){owner(m);const v=p.policies;assert(v.currency==='IDR','Ruang kerja ini menggunakan rupiah.');try{new Intl.DateTimeFormat('en',{timeZone:v.timezone}).format(new Date())}catch{throw new AppError('Zona waktu IANA tidak valid.');}assert(['handover','completed'].includes(v.recognition),'Kebijakan pengakuan tidak valid.');assert(Array.isArray(v.units)&&v.units.length&&new Set(v.units.map(x=>x.id)).size===v.units.length,'Unit bisnis harus unik.');for(const t of s.transactions)assert(v.units.some(x=>x.id===t.unit),'Unit yang telah digunakan tidak dapat dihapus.');s.policies={...s.policies,...v,approved:true,approvedBy:m.id,approvedAt:now(),fixture:false};for(const t of s.transactions.filter(t=>t.holdReason==='Kebijakan pengakuan belum disetujui.')){t.holdReason='';t.status='Diajukan';}action='Sahkan kebijakan akuntansi';}
 else if(path==='/api/snapshot'){reviewer(m);const f=filter(p.filter);const snap=snapshot(s,w.operations,f,m,p.status==='Final'?'Final':'Draft',p.label||'Paket laporan');objectId=snap.id;action='Buat snapshot '+snap.status;}
 else if(path==='/api/period'){owner(m);const f=filter(p.period);let period=s.periods.find(x=>x.id===p.id);if(!period){assert(!s.periods.some(x=>f.start<=x.end&&f.end>=x.start),'Periode bertumpang tindih.');period={id:'PER-'+id(),...f,status:'Open'};s.periods.push(period);}assert(['Open','Review','Closed'].includes(p.status),'Status periode tidak valid.');if(p.status==='Closed'){gate(s,w.operations,{...period,unit:'',customer:'',source:''});assert(s.snapshots.some(x=>x.status==='Final'&&x.filter.start===period.start&&x.filter.end===period.end&&!x.filter.unit&&!x.superseded&&eq(x.journalIds,F.report(s,{start:period.start,end:period.end,unit:'',customer:'',source:''}).balanceJournals.map(j=>j.id))),'Buat paket Final semua unit sebelum menutup periode.');}if(period.status==='Closed'&&p.status!=='Closed'){assert(String(p.reason||'').length>=5,'Alasan membuka periode wajib diisi.');for(const snap of s.snapshots.filter(x=>x.status==='Final'&&x.filter.start<=period.end&&x.filter.end>=period.start))snap.superseded=true;}period.status=p.status;period.updatedBy=m.id;period.updatedAt=now();period.reason=p.reason||'';action='Ubah periode ke '+p.status;}
 else if(path==='/api/bank-import'){reviewer(m);assert(Array.isArray(p.rows)&&p.rows.length<=1000,'Impor maksimal 1.000 baris per berkas.');for(const row of p.rows){assert(F.dateValid(row.date)&&F.accountMap[row.account]?.cash,'Tanggal atau akun mutasi tidak valid.');F.amount(row.amount,false);assert(row.amount!==0&&row.reference,'Nominal dan referensi mutasi wajib diisi.');const key=[row.account,row.date,row.reference,row.amount].join('|');if(!s.bankRows.some(x=>x.key===key))s.bankRows.push({...row,id:'BANK-'+id(),key,importedBy:m.id,importedAt:now(),matchedId:''});}action='Impor mutasi untuk rekonsiliasi';}
 else if(path==='/api/match'){reviewer(m);const row=s.bankRows.find(x=>x.id===p.id),t=s.transactions.find(x=>x.id===p.transactionId);assert(row&&t&&t.status==='Tercatat','Pilih mutasi dan transaksi tercatat.');assert(!row.matchedId&&!s.bankRows.some(x=>x.matchedId===t.id),'Mutasi atau transaksi sudah dicocokkan.');const j=s.journals.find(j=>j.transactionId===t.id),net=j.lines.filter(l=>l.account===row.account).reduce((n,l)=>n+l.debit-l.credit,0);assert(net===row.amount,'Nominal bersih dan rekening harus sama.');assert(t.createdBy!==m.id,'Rekonsiliasi memerlukan pemeriksa berbeda dari pencatat.');row.matchedId=t.id;row.matchedBy=m.id;row.matchedAt=now();action='Cocokkan mutasi bank';}
 else if(path==='/api/insight'){reviewer(m);const v={id:p.id||'INS-'+id(),status:p.status||'Open',reason:String(p.reason||''),assignee:String(p.assignee||''),due:p.due||'',updatedAt:now(),updatedBy:m.id};assert(['Open','Investigating','Resolved','Dismissed'].includes(v.status),'Status tindak lanjut tidak valid.');if(['Resolved','Dismissed'].includes(v.status))assert(v.reason.length>=5,'Alasan penyelesaian wajib diisi.');const i=s.insights.findIndex(x=>x.id===v.id);if(i<0)s.insights.push(v);else s.insights[i]=v;action='Tindak lanjut deteksi';}
 else if(path==='/api/budget'){owner(m);assert(F.dateValid(p.date)&&s.policies.units.some(x=>x.id===p.unit),'Bulan atau unit anggaran tidak valid.');const row={id:p.id||'BUD-'+id(),date:p.date.slice(0,7)+'-01',unit:p.unit,account:p.account,amount:F.amount(p.amount),createdBy:m.id};assert(F.accountMap[row.account],'Akun tidak valid.');const i=s.budgets.findIndex(x=>x.date===row.date&&x.unit===row.unit&&x.account===row.account);if(i<0)s.budgets.push(row);else s.budgets[i]=row;action='Simpan anggaran';}
 else if(path==='/api/cash-closing'){const rows=s.transactions.filter(t=>t.kind==='receipt'&&t.method==='Cash'&&t.status==='Tercatat'&&!t.fixture&&!t.settlementId&&t.date<=p.date);assert(rows.length,'Tidak ada penerimaan cash yang belum closing.');assert(F.dateValid(p.date),'Tanggal closing tidak valid.');assert(w.operations.employees.some(e=>e.id===p.witness&&e.active)&&p.witness!==parse(m.profile||'{}').employeeId,'Pilih saksi aktif berbeda dari petugas.');const expectedDeposit=rows.reduce((n,t)=>n+t.amount,0),float=F.amount(p.float,false),physical=F.amount(p.physical,false),recount=F.amount(p.recount,false);assert(float>=0&&physical>=float&&physical===recount,'Hitung ulang dan uang fisik harus sama; fisik tidak boleh kurang dari float.');const difference=physical-float-expectedDeposit;assert(!difference||String(p.note||'').length>=5,'Selisih memerlukan penjelasan dan tindak lanjut.');assert(p.envelope&&p.seal&&p.confirmed,'Lengkapi amplop, segel, dan pemeriksaan.');const st={id:'CASH-'+id(),date:p.date,shift:p.shift,float,physical,recount,expectedDeposit,deposit:physical-float,difference,witness:w.operations.employees.find(e=>e.id===p.witness).name,depositor:p.depositor,envelope:p.envelope,seal:p.seal,keyHolder:p.keyHolder,note:p.note,unitAmounts:Object.fromEntries([...new Set(rows.map(t=>t.unit))].map(unit=>[unit,rows.filter(t=>t.unit===unit).reduce((n,t)=>n+t.amount,0)])),paymentIds:rows.map(t=>t.id),orderIds:[...new Set(rows.map(t=>t.orderId).filter(Boolean))],receiptIds:rows.map(t=>t.receiptNo),status:'Belum Disetor',createdAt:now(),createdBy:m.name,createdById:m.id};for(const t of rows)t.settlementId=st.id;w.operations.settlements.unshift(st);action='Closing seluruh penerimaan cash berdasarkan Payment ID';objectId=st.id;}
 else if(path==='/api/migration'){owner(m);assert(TH.validateBackup(p.operations),'Cadangan operasional tidak valid.');for(const key of ['tenants','employees','orders','invoices','reports','evaluations','settlements','requests']){const existing=new Set(w.operations[key].map(x=>x.id));for(const item of p.operations[key])if(!existing.has(item.id))w.operations[key].push(item);}scan(w,m);action='Migrasi data baru dengan pratinjau';}
 else if(path==='/api/readiness'){owner(m);assert(['backupRestore','deviceTrial','sopEvidence','bankSetup'].includes(p.check),'Pemeriksaan tidak dikenal.');w.readiness={...(w.readiness||{}),[p.check]:{confirmed:!!p.confirmed,by:m.id,at:now()}};action='Konfirmasi kesiapan '+p.check;}
 else if(path==='/api/member'){owner(m);assert(p.id!==w.ownerId,'Owner utama tidak dapat dinonaktifkan.');assert(['Owner','Finance','Operator','Konsumen'].includes(p.role)&&['Aktif','Nonaktif','Menunggu'].includes(p.status),'Akses tidak valid.');const exists=await first(env,'SELECT id FROM members WHERE id=?',p.id);assert(exists,'Pengguna harus masuk ke situs terlebih dahulu.');if(p.employeeId)assert(w.operations.employees.some(e=>e.id===p.employeeId&&e.active),'Karyawan terkait harus aktif.');if(p.customerId)assert(w.operations.tenants.some(t=>t.id===p.customerId),'Penghuni terkait tidak ditemukan.');if(p.status==='Aktif'&&p.role==='Operator')assert(p.employeeId,'Tautkan karyawan aktif untuk Operator.');if(p.status==='Aktif'&&p.role==='Konsumen')assert(p.customerId,'Tautkan penghuni untuk Konsumen.');const other=(await stmt(env,'SELECT id,status,profile FROM members').all()).results.filter(x=>x.id!==p.id&&x.status==='Aktif');if(p.status==='Aktif')assert(!other.some(x=>{const z=parse(x.profile||'{}');return p.employeeId&&z.employeeId===p.employeeId||p.customerId&&z.customerId===p.customerId}),'Profil telah dipakai akun aktif lain.');w.memberChange=p;action='Ubah akses anggota';}
 else throw new AppError('Endpoint tidak ditemukan.',404);
 const result=await save(env,w,old,m,action,objectId,p.mutationId);return json({...result,objectId});
}
export default {async scheduled(event,env,ctx){ctx.waitUntil(runScheduled(env).catch(e=>{console.error('Draft schedule failed',e.message);throw e;}));},async fetch(req,env){try{return await route(req,env)}catch(e){if(!e.status)console.error('Top Hills request failed',e.message);return json({error:e.status?e.message:'Penyimpanan belum dapat menyelesaikan permintaan. Input tetap tersedia; coba kembali.',detail:e.status?undefined:undefined},e.status||503)}}};
