import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const workspace = sqliteTable('workspace', {id:text('id').primaryKey(), revision:integer('revision').notNull().default(0), data:text('data').notNull(), updatedAt:text('updated_at').notNull()});
export const members = sqliteTable('members', {id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role').notNull(),status:text('status').notNull(),profile:text('profile').notNull().default(''),createdAt:text('created_at').notNull()});
export const transactions = sqliteTable('finance_transactions', {id:text('id').primaryKey(),sourceKey:text('source_key').notNull(),kind:text('kind').notNull(),unit:text('unit').notNull(),customer:text('customer').notNull().default(''),date:text('date').notNull(),status:text('status').notNull(),createdBy:text('created_by').notNull(),data:text('data').notNull()},t=>[uniqueIndex('txn_source_unique').on(t.sourceKey),index('txn_date_unit').on(t.date,t.unit),index('txn_status').on(t.status)]);
export const journals = sqliteTable('journals', {id:text('id').primaryKey(),transactionId:text('transaction_id').notNull(),date:text('date').notNull(),unit:text('unit').notNull(),data:text('data').notNull()},t=>[uniqueIndex('journal_transaction_unique').on(t.transactionId),index('journal_date_unit').on(t.date,t.unit)]);
export const journalLines = sqliteTable('journal_lines', {id:text('id').primaryKey(),journalId:text('journal_id').notNull(),account:text('account').notNull(),date:text('date').notNull(),unit:text('unit').notNull(),customer:text('customer').notNull().default(''),debit:integer('debit').notNull().default(0),credit:integer('credit').notNull().default(0),cashCategory:text('cash_category').notNull().default('')},t=>[index('lines_account_date_unit').on(t.account,t.date,t.unit),index('lines_journal').on(t.journalId)]);
export const attachments = sqliteTable('attachments',{id:text('id').primaryKey(),objectId:text('object_id').notNull(),key:text('object_key').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('proof_object').on(t.objectId),index('proof_hash').on(t.hash)]);
export const records = sqliteTable('finance_records', {id:text('id').primaryKey(),kind:text('kind').notNull(),date:text('date').notNull(),data:text('data').notNull()},t=>[index('records_kind_date').on(t.kind,t.date)]);
export const mutations = sqliteTable('mutations',{id:text('id').primaryKey(),actor:text('actor').notNull(),createdAt:text('created_at').notNull(),result:text('result').notNull()});
export const audit = sqliteTable('finance_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),at:text('at').notNull(),action:text('action').notNull(),objectId:text('object_id').notNull(),data:text('data').notNull()},t=>[index('audit_date').on(t.at)]);

// SOP v0.4: independently versioned records; no portal data in workspace JSON.
export const laundryRooms=sqliteTable('laundry_rooms',{id:text('id').primaryKey(),tokenHash:text('token_hash'),revision:integer('revision').notNull().default(0),data:text('data').notNull()},t=>[uniqueIndex('room_token_unique').on(t.tokenHash)]);
export const laundryOrders=sqliteTable('laundry_orders',{id:text('id').primaryKey(),roomId:text('room_id').notNull(),tokenHash:text('token_hash').notNull(),submissionKey:text('submission_key').notNull(),revision:integer('revision').notNull().default(1),status:text('status').notNull(),createdAt:text('created_at').notNull(),data:text('data').notNull()},t=>[uniqueIndex('laundry_submission_unique').on(t.submissionKey),uniqueIndex('laundry_token_unique').on(t.tokenHash),index('laundry_date_status').on(t.createdAt,t.status),index('laundry_room').on(t.roomId)]);
export const laundryCounters=sqliteTable('laundry_counters',{id:text('id').primaryKey(),value:integer('value').notNull()});
export const laundryEvents=sqliteTable('laundry_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),actor:text('actor').notNull(),at:text('at').notNull(),action:text('action').notNull(),data:text('data').notNull()},t=>[index('laundry_event_order').on(t.orderId,t.at)]);
export const laundryProofs=sqliteTable('laundry_proofs',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),key:text('object_key').notNull(),mime:text('mime').notNull(),capture:text('capture').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('laundry_proof_order').on(t.orderId)]);
export const laundryMutations=sqliteTable('laundry_mutations',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),hash:text('hash').notNull(),result:text('result').notNull()});
export const staffSessions=sqliteTable('staff_sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),cipher:text('cipher').notNull(),expiresAt:integer('expires_at').notNull(),tokenExpiresAt:integer('token_expires_at').notNull(),leaseUntil:integer('lease_until').notNull().default(0),createdAt:integer('created_at').notNull(),lastSeen:integer('last_seen').notNull(),device:text('device').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[index('session_user').on(t.userId),index('session_expiry').on(t.expiresAt)]);
export const authLimits=sqliteTable('auth_limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
// Demo sessions are isolated from all operational orders, proofs and finance.
export const laundryDemoSessions=sqliteTable('laundry_demo_sessions',{id:text('id').primaryKey(),revision:integer('revision').notNull().default(0),expiresAt:integer('expires_at').notNull(),data:text('data').notNull()},t=>[index('demo_session_expiry').on(t.expiresAt)]);
