import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {readFile,mkdir,writeFile,cp,readdir,stat} from 'node:fs/promises';
import path from 'node:path';
await build({entryPoints:['scripts/qr-entry.cjs'],outfile:'dist/vendor/room-qr.js',bundle:true,minify:true,platform:'browser'});
await build({entryPoints:['scripts/laundry-demo-entry.mjs'],outfile:'dist/sop-demo.js',bundle:true,minify:true,platform:'browser'});
const {PDFDocument,StandardFonts,rgb}= (await import('../dist/vendor/pdf-lib.min.js')).default;
const fixture=await PDFDocument.create();fixture.setCreationDate(new Date('2026-09-10T00:00:00Z'));fixture.setModificationDate(new Date('2026-09-10T00:00:00Z'));const fp=fixture.addPage([595,842]),ff=await fixture.embedFont(StandardFonts.Helvetica),fb=await fixture.embedFont(StandardFonts.HelveticaBold);fp.drawRectangle({x:0,y:710,width:595,height:132,color:rgb(.08,.17,.3)});fp.drawText('TOP HILLS & CO',{x:50,y:770,size:25,font:fb,color:rgb(1,1,1)});fp.drawText('BUKTI LATIHAN - SELURUHNYA FIKTIF',{x:50,y:738,size:13,font:fb,color:rgb(.8,.88,1)});let fy=650;for(const text of ['Referensi: BUKTI-FIKTIF-001','Periode contoh: 9 - 11 September 2026','Dokumen demonstrasi untuk fixture requirement Menu Laporan.','Rincian nilai setiap transaksi tersedia pada jurnal yang ditautkan.','','Ini bukan kuitansi pembayaran, mutasi bank, atau persetujuan nyata.','Nama, nominal, dan transaksi hanya digunakan untuk pengujian.','','Catatan pemeriksaan fixture:','10 September: laba Rp50.000, kas akhir Rp4.500.000.','11 September: laba Rp70.000, kas akhir Rp5.000.000.','Gabungan: laba Rp120.000; aset Rp13.020.000.']){fp.drawText(text,{x:50,y:fy,size:12,font:ff,color:rgb(.1,.2,.33)});fy-=29;}await writeFile('dist/assets/Bukti-latihan-Top-Hills.pdf',await fixture.save());
const root=process.cwd(),pub=path.join(root,'dist'),assets={};
async function walk(dir,prefix=''){for(const n of await readdir(dir)){if(n.startsWith('.')||n==='server'||n==='vendor'&&false)continue;const p=path.join(dir,n),url=prefix+'/'+n,s=await stat(p);if(s.isDirectory())await walk(p,url);else if(/\.(html|css|js|png|pdf|ico|woff2|md|sql)$/.test(n))assets[url]={data:(await readFile(p)).toString('base64'),mime:({'html':'text/html; charset=utf-8','css':'text/css; charset=utf-8','js':'application/javascript; charset=utf-8','png':'image/png','pdf':'application/pdf','woff2':'font/woff2','md':'text/plain; charset=utf-8','sql':'text/plain; charset=utf-8'})[n.split('.').pop()]||'application/octet-stream'};}}
await walk(pub);for(const a of Object.values(assets))a.etag=createHash('sha256').update(a.data).digest('hex');await mkdir('.sites-runtime',{recursive:true});await writeFile('.sites-runtime/assets.json',JSON.stringify(assets));
await build({entryPoints:['server/worker.mjs'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,external:['cloudflare:workers']});
await mkdir('dist/.openai',{recursive:true});await cp('.openai/hosting.json','dist/.openai/hosting.json');await cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Built Top Hills Worker, protected finance API, assets and migrations.');
